/***************************************************************************//**
* File Name: cycfg_gatt_db.h
* Version: 2.20
*
* Description:
* Definitions for constants used in the device's GATT database and function
* prototypes.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.20.0.3018
*
********************************************************************************
* Copyright 2020 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_GATT_DB_H)
#define CYCFG_GATT_DB_H

#include "stdint.h"
#include "wiced_bt_ota_firmware_upgrade.h"

#define __UUID_SERVICE_GENERIC_ACCESS                                   0x1800
#define __UUID_CHARACTERISTIC_DEVICE_NAME                               0x2A00
#define __UUID_CHARACTERISTIC_APPEARANCE                                0x2A01
#define __UUID_SERVICE_GENERIC_ATTRIBUTE                                0x1801
#define __UUID_SERVICE_BT101                                            0x06u, 0xF9u, 0xF4u, 0xE4u, 0x53u, 0xACu, 0x49u, 0x8Fu, 0x1Du, 0x48u, 0xEFu, 0xA4u, 0xB5u, 0xDEu, 0xC2u, 0xFDu
#define __UUID_CHARACTERISTIC_BT101_COUNTER                             0x14u, 0x43u, 0x05u, 0x41u, 0x15u, 0x1Cu, 0x23u, 0xB3u, 0x3Eu, 0x45u, 0xC7u, 0xC5u, 0xAAu, 0xECu, 0x0Au, 0x52u
#define __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION           0x2902
#define __UUID_DESCRIPTOR_CHARACTERISTIC_USER_DESCRIPTION               0x2901
#define __UUID_SERVICE_CUSTOM_OTA_FIRMWARE_UPGRADE                      0x1Fu, 0x38u, 0xA1u, 0x38u, 0xADu, 0x82u, 0x35u, 0x86u, 0xA0u, 0x43u, 0x13u, 0x5Cu, 0x47u, 0x1Eu, 0x5Du, 0xAEu
#define __UUID_CHARACTERISTIC_CONTROL_POINT                             0x1Bu, 0x66u, 0x6Cu, 0x08u, 0x0Au, 0x57u, 0x8Eu, 0x83u, 0x99u, 0x4Eu, 0xA7u, 0xF7u, 0xBFu, 0x50u, 0xDDu, 0xA3u
#define __UUID_CHARACTERISTIC_DATA                                      0x26u, 0xFEu, 0x2Eu, 0xE7u, 0x09u, 0x24u, 0x4Fu, 0xB7u, 0x91u, 0x40u, 0x61u, 0xD9u, 0x7Au, 0x6Cu, 0xE8u, 0xA2u

/* Service Generic Access */
#define HDLS_GAP                                                        0x01
/* Characteristic Device Name */
#define HDLC_GAP_DEVICE_NAME                                            0x02
#define HDLC_GAP_DEVICE_NAME_VALUE                                      0x03
/* Characteristic Appearance */
#define HDLC_GAP_APPEARANCE                                             0x04
#define HDLC_GAP_APPEARANCE_VALUE                                       0x05

/* Service Generic Attribute */
#define HDLS_GATT                                                       0x06

/* Service BT101 */
#define HDLS_BT101                                                      0x07
/* Characteristic Counter */
#define HDLC_BT101_COUNTER                                              0x08
#define HDLC_BT101_COUNTER_VALUE                                        0x09
/* Descriptor Client Characteristic Configuration */
#define HDLD_BT101_COUNTER_CLIENT_CHAR_CONFIG                           0x0A
/* Descriptor Characteristic User Description */
#define HDLD_BT101_COUNTER_CHAR_USER_DESCRIPTION                        0x0B

/* Service Custom OTA Firmware Upgrade */
#define HDLS_OTA_FW_UPGRADE_SERVICE                                     HANDLE_OTA_FW_UPGRADE_SERVICE
/* Characteristic Control Point */
#define HDLC_OTA_FW_UPGRADE_SERVICE_CONTROL_POINT                       HANDLE_OTA_FW_UPGRADE_CHARACTERISTIC_CONTROL_POINT
#define HDLC_OTA_FW_UPGRADE_SERVICE_CONTROL_POINT_VALUE                 HANDLE_OTA_FW_UPGRADE_CONTROL_POINT
/* Descriptor Client Characteristic Configuration */
#define HDLD_OTA_FW_UPGRADE_SERVICE_CONTROL_POINT_CLIENT_CHAR_CONFIG    HANDLE_OTA_FW_UPGRADE_CLIENT_CONFIGURATION_DESCRIPTOR
/* Characteristic Data */
#define HDLC_OTA_FW_UPGRADE_SERVICE_DATA                                HANDLE_OTA_FW_UPGRADE_CHARACTERISTIC_DATA
#define HDLC_OTA_FW_UPGRADE_SERVICE_DATA_VALUE                          HANDLE_OTA_FW_UPGRADE_DATA

/* External Lookup Table Entry */
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table_t;

/* External definitions */
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[];
extern const uint16_t app_gatt_db_ext_attr_tbl_size;
extern uint8_t app_gap_device_name[];
extern const uint16_t app_gap_device_name_len;
extern uint8_t app_gap_appearance[];
extern const uint16_t app_gap_appearance_len;
extern uint8_t app_bt101_counter[];
extern const uint16_t app_bt101_counter_len;
extern uint8_t app_bt101_counter_client_char_config[];
extern const uint16_t app_bt101_counter_client_char_config_len;
extern uint8_t app_bt101_counter_char_user_description[];
extern const uint16_t app_bt101_counter_char_user_description_len;
extern uint8_t app_ota_fw_upgrade_service_control_point[];
extern const uint16_t app_ota_fw_upgrade_service_control_point_len;
extern uint8_t app_ota_fw_upgrade_service_control_point_client_char_config[];
extern const uint16_t app_ota_fw_upgrade_service_control_point_client_char_config_len;
extern uint8_t app_ota_fw_upgrade_service_data[];
extern const uint16_t app_ota_fw_upgrade_service_data_len;

#endif /* CYCFG_GATT_DB_H */

