/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * Definitions for constants used in the device's GATT database and function
 * prototypes.
 *
 */

// ex04_ble_manu_db.h

#ifndef __GATT_DATABASE_H__
#define __GATT_DATABASE_H__

#define __UUID_WICED101                       0x01, 0xee, 0x1f, 0x93, 0x07, 0xfc, 0x40, 0x99, 0x99, 0xbc, 0x55, 0x96, 0xec, 0x3a, 0xb9, 0x5b
#define __UUID_WICED101_LED                   0xfd, 0x01, 0xe4, 0x3b, 0xd7, 0x56, 0x4b, 0x2f, 0x98, 0x19, 0xde, 0x07, 0x56, 0x54, 0x32, 0x5d
#define __UUID_WICED101_BUTTON                0xb1, 0xfa, 0x18, 0x1a, 0xb6, 0xaa, 0x44, 0x40, 0xbf, 0x6f, 0x57, 0xc2, 0x54, 0xb2, 0x33, 0xea

// ***** Primary Service 'Generic Attribute'
#define HDLS_GENERIC_ATTRIBUTE                0x0001

// ***** Primary Service 'Generic Access'
#define HDLS_GENERIC_ACCESS                   0x0014
// ----- Characteristic 'Device Name'
#define HDLC_GENERIC_ACCESS_DEVICE_NAME       0x0015
#define HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE 0x0016
// ----- Characteristic 'Appearance'
#define HDLC_GENERIC_ACCESS_APPEARANCE        0x0017
#define HDLC_GENERIC_ACCESS_APPEARANCE_VALUE  0x0018

// ***** Primary Service 'Wiced101'
#define HDLS_WICED101                         0x0028
// ----- Characteristic 'LED'
#define HDLC_WICED101_LED                     0x0029
#define HDLC_WICED101_LED_VALUE               0x002A
// ----- Characteristic 'Button'
#define HDLC_WICED101_BUTTON                  0x002B
#define HDLC_WICED101_BUTTON_VALUE            0x002C
// ===== CCCD
#define HDLD_WICED101_BUTTON_CLIENT_CONFIGURATION 0x002D

// External Lookup Table Entry
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table;

// External definitions
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table ex04_ble_manu_gatt_db_ext_attr_tbl[];
extern const uint16_t ex04_ble_manu_gatt_db_ext_attr_tbl_size;
extern uint8_t BT_LOCAL_NAME[];
extern const uint16_t BT_LOCAL_NAME_CAPACITY;

#endif /* __GATT_DATABASE_H__ */
