#
# This file has been automatically generated by the WICED 20719-B1 Designer.
#

APP_SRC =  ex03_ota_secure.c
APP_SRC += ex03_ota_secure_db.c
APP_SRC += wiced_bt_cfg.c
APP_SRC += ecdsa256_pub.c

C_FLAGS += -DWICED_BT_TRACE_ENABLE

$(NAME)_COMPONENTS := fw_upgrade_lib.a

# If defined, HCI traces are sent over transport/WICED HCI interface
C_FLAGS += -DHCI_TRACE_OVER_TRANSPORT

########################################################################
################ DO NOT MODIFY FILE BELOW THIS LINE ####################
########################################################################

