/***************************************************************************//**
* File Name: cycfg_gatt_db.c
* Version: 1.1
*
* Description:
* BLE device's GATT database and device configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 1.1.0 build 291
*
********************************************************************************
* Copyright 2019 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_gatt_db.h"
#include "wiced_bt_uuid.h"
#include "wiced_bt_gatt.h"

/*************************************************************************************
* GATT server definitions
*************************************************************************************/

const uint8_t gatt_database[] = 
{
    /* Primary Service: Generic Access */
    PRIMARY_SERVICE_UUID16 (HDLS_GAP, __UUID_SERVICE_GENERIC_ACCESS),
        /* Characteristic: Device Name */
        CHARACTERISTIC_UUID16 (HDLC_GAP_DEVICE_NAME, HDLC_GAP_DEVICE_NAME_VALUE, __UUID_CHARACTERISTIC_DEVICE_NAME, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: Appearance */
        CHARACTERISTIC_UUID16 (HDLC_GAP_APPEARANCE, HDLC_GAP_APPEARANCE_VALUE, __UUID_CHARACTERISTIC_APPEARANCE, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),

    /* Primary Service: Generic Attribute */
    PRIMARY_SERVICE_UUID16 (HDLS_GATT, __UUID_SERVICE_GENERIC_ATTRIBUTE),

    /* Primary Service: Modus */
    PRIMARY_SERVICE_UUID128 (HDLS_MODUS, __UUID_SERVICE_MODUS),
        /* Characteristic: Counter */
        CHARACTERISTIC_UUID128 (HDLC_MODUS_COUNTER, HDLC_MODUS_COUNTER_VALUE, __UUID_CHARACTERISTIC_MODUS_COUNTER, LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_NOTIFY, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_AUTH_READABLE),
            /* Descriptor: Client Characteristic Configuration */
            CHAR_DESCRIPTOR_UUID16_WRITABLE (HDLD_MODUS_COUNTER_CLIENT_CHAR_CONFIG, __UUID_DESCRIPTOR_CLIENT_CHARACTERISTIC_CONFIGURATION, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ | LEGATTDB_PERM_AUTH_READABLE | LEGATTDB_PERM_AUTH_WRITABLE),
            /* Descriptor: Characteristic User Description */
            CHAR_DESCRIPTOR_UUID16 (HDLD_MODUS_COUNTER_CHAR_USER_DESCRIPTION, __UUID_DESCRIPTOR_CHARACTERISTIC_USER_DESCRIPTION, LEGATTDB_PERM_READABLE),
};

/* Length of the GATT database */
const uint16_t gatt_database_len = sizeof(gatt_database);

/*************************************************************************************
 * GATT Initial Value Arrays
 ************************************************************************************/
 
uint8_t app_gap_device_name[]                     = {'k', 'e', 'y', '_', 'p', 'a', 'i', 'r', };
uint8_t app_gap_appearance[]                      = {0x00u, 0x00u, };
uint8_t app_modus_counter[]                       = {0x00u, };
uint8_t app_modus_counter_client_char_config[]    = {0x00u, 0x00u, };
uint8_t app_modus_counter_char_user_description[] = {'C', 'o', 'u', 'n', 't', ' ', 'o', 'f', ' ', 'b', 'u', 't', 't', 'o', 'n', ' ', 'p', 'r', 'e', 's', 's', 'e', 's', };
 
 /************************************************************************************
 * GATT Lookup Table
 ************************************************************************************/
 
gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[] =
{
    /* { attribute handle,                      maxlen, curlen, attribute data } */
    { HDLC_GAP_DEVICE_NAME_VALUE,               8,      8,      app_gap_device_name },
    { HDLC_GAP_APPEARANCE_VALUE,                2,      2,      app_gap_appearance },
    { HDLC_MODUS_COUNTER_VALUE,                 1,      1,      app_modus_counter },
    { HDLD_MODUS_COUNTER_CLIENT_CHAR_CONFIG,    2,      2,      app_modus_counter_client_char_config },
    { HDLD_MODUS_COUNTER_CHAR_USER_DESCRIPTION, 23,     23,     app_modus_counter_char_user_description },
};

/* Number of Lookup Table entries */
const uint16_t app_gatt_db_ext_attr_tbl_size = (sizeof(app_gatt_db_ext_attr_tbl) / sizeof(gatt_db_lookup_table_t));

/* Number of GATT initial value arrays entries */
const uint16_t app_gap_device_name_len = (sizeof(app_gap_device_name));
const uint16_t app_gap_appearance_len = (sizeof(app_gap_appearance));
const uint16_t app_modus_counter_len = (sizeof(app_modus_counter));
const uint16_t app_modus_counter_client_char_config_len = (sizeof(app_modus_counter_client_char_config));
const uint16_t app_modus_counter_char_user_description_len = (sizeof(app_modus_counter_char_user_description));

