/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * Definitions for constants used in the device's GATT database and function
 * prototypes.
 *
 */

// ex05_ota_db.h

#ifndef __GATT_DATABASE_H__
#define __GATT_DATABASE_H__

#define __UUID_WICEDLED                       0xf1, 0xe8, 0xd1, 0x28, 0x57, 0xf9, 0x42, 0xaf, 0xb0, 0xec, 0xe0, 0x65, 0x70, 0xc1, 0x3d, 0xf8
#define __UUID_WICEDLED_LED                   0xd7, 0x14, 0xdd, 0x68, 0xd4, 0x3b, 0x44, 0x85, 0x8e, 0x11, 0x22, 0x65, 0x5f, 0x9f, 0xca, 0x45

// ***** Primary Service 'Generic Attribute'
#define HDLS_GENERIC_ATTRIBUTE                0x0001

// ***** Primary Service 'Generic Access'
#define HDLS_GENERIC_ACCESS                   0x0014
// ----- Characteristic 'Device Name'
#define HDLC_GENERIC_ACCESS_DEVICE_NAME       0x0015
#define HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE 0x0016
// ----- Characteristic 'Appearance'
#define HDLC_GENERIC_ACCESS_APPEARANCE        0x0017
#define HDLC_GENERIC_ACCESS_APPEARANCE_VALUE  0x0018

// ***** Primary Service 'WicedLED'
#define HDLS_WICEDLED                         0x0028
// ----- Characteristic 'LED'
#define HDLC_WICEDLED_LED                     0x0029
#define HDLC_WICEDLED_LED_VALUE               0x002A

// External Lookup Table Entry
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table;

// External definitions
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table ex05_ota_gatt_db_ext_attr_tbl[];
extern const uint16_t ex05_ota_gatt_db_ext_attr_tbl_size;
extern uint8_t BT_LOCAL_NAME[];
extern const uint16_t BT_LOCAL_NAME_CAPACITY;

#endif /* __GATT_DATABASE_H__ */
