/***************************************************************************//**
* File Name: cycfg_gatt_db.h
* Version: 2.0
*
* Description:
* Definitions for constants used in the device's GATT database and function
* prototypes.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.0.0.1367
*
********************************************************************************
* Copyright 2019 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_GATT_DB_H)
#define CYCFG_GATT_DB_H

#include "stdint.h"

#define __UUID_SERVICE_GENERIC_ACCESS               0x1800
#define __UUID_CHARACTERISTIC_DEVICE_NAME           0x2A00
#define __UUID_CHARACTERISTIC_APPEARANCE            0x2A01
#define __UUID_SERVICE_GENERIC_ATTRIBUTE            0x1801
#define __UUID_SERVICE_MODUS101                     0xA5u, 0xFDu, 0xFEu, 0x50u, 0x7Eu, 0x6Eu, 0xE7u, 0x84u, 0xD1u, 0x46u, 0xA3u, 0x6Bu, 0x48u, 0xC8u, 0x07u, 0xD4u
#define __UUID_CHARACTERISTIC_MODUS101_LED          0xF0u, 0x8Au, 0x24u, 0x40u, 0x8Eu, 0x8Au, 0x3Du, 0x86u, 0xD4u, 0x49u, 0x61u, 0xC7u, 0x5Fu, 0x3Au, 0xAFu, 0x36u
#define __UUID_CHARACTERISTIC_MODUS101_BUTTON       0x10u, 0x67u, 0x03u, 0x10u, 0x8Cu, 0x6Du, 0x32u, 0x8Eu, 0x86u, 0x42u, 0x08u, 0xADu, 0x10u, 0x41u, 0xBDu, 0xB2u

/* Service Generic Access */
#define HDLS_GAP                                    0x01
/* Characteristic Device Name */
#define HDLC_GAP_DEVICE_NAME                        0x02
#define HDLC_GAP_DEVICE_NAME_VALUE                  0x03
/* Characteristic Appearance */
#define HDLC_GAP_APPEARANCE                         0x04
#define HDLC_GAP_APPEARANCE_VALUE                   0x05

/* Service Generic Attribute */
#define HDLS_GATT                                   0x06

/* Service Modus101 */
#define HDLS_MODUS101                               0x07
/* Characteristic LED */
#define HDLC_MODUS101_LED                           0x08
#define HDLC_MODUS101_LED_VALUE                     0x09
/* Characteristic Button */
#define HDLC_MODUS101_BUTTON                        0x0A
#define HDLC_MODUS101_BUTTON_VALUE                  0x0B

/* External Lookup Table Entry */
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table_t;

/* External definitions */
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[];
extern const uint16_t app_gatt_db_ext_attr_tbl_size;
extern uint8_t app_gap_device_name[];
extern const uint16_t app_gap_device_name_len;
extern uint8_t app_gap_appearance[];
extern const uint16_t app_gap_appearance_len;
extern uint8_t app_modus101_led[];
extern const uint16_t app_modus101_led_len;
extern uint8_t app_modus101_button[];
extern const uint16_t app_modus101_button_len;

#endif /* CYCFG_GATT_DB_H */

