/***************************************************************************//**
* File Name: cycfg_gatt_db.h
* Version: 2.20
*
* Description:
* Definitions for constants used in the device's GATT database and function
* prototypes.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.20.0.3018
*
********************************************************************************
* Copyright 2020 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_GATT_DB_H)
#define CYCFG_GATT_DB_H

#include "stdint.h"

#define __UUID_SERVICE_GENERIC_ACCESS               0x1800
#define __UUID_CHARACTERISTIC_DEVICE_NAME           0x2A00
#define __UUID_CHARACTERISTIC_APPEARANCE            0x2A01
#define __UUID_SERVICE_GENERIC_ATTRIBUTE            0x1801
#define __UUID_SERVICE_BT101                        0xB1u, 0x7Cu, 0x43u, 0x05u, 0xFDu, 0x0Fu, 0x81u, 0x84u, 0xB0u, 0x42u, 0x86u, 0x0Bu, 0x69u, 0xCDu, 0x33u, 0x11u
#define __UUID_CHARACTERISTIC_BT101_LED             0x01u, 0xEFu, 0x01u, 0xEEu, 0x5Au, 0xFCu, 0xB9u, 0xBBu, 0xB2u, 0x43u, 0xC0u, 0x04u, 0xB8u, 0x1Du, 0x6Fu, 0x34u
#define __UUID_CHARACTERISTIC_BT101_BUTTON          0xFFu, 0xC0u, 0x5Fu, 0xE8u, 0x01u, 0x12u, 0xE6u, 0xA1u, 0x30u, 0x47u, 0xA2u, 0x08u, 0xE4u, 0x18u, 0xF2u, 0x5Eu

/* Service Generic Access */
#define HDLS_GAP                                    0x01
/* Characteristic Device Name */
#define HDLC_GAP_DEVICE_NAME                        0x02
#define HDLC_GAP_DEVICE_NAME_VALUE                  0x03
/* Characteristic Appearance */
#define HDLC_GAP_APPEARANCE                         0x04
#define HDLC_GAP_APPEARANCE_VALUE                   0x05

/* Service Generic Attribute */
#define HDLS_GATT                                   0x06

/* Service BT101 */
#define HDLS_BT101                                  0x07
/* Characteristic LED */
#define HDLC_BT101_LED                              0x08
#define HDLC_BT101_LED_VALUE                        0x09
/* Characteristic Button */
#define HDLC_BT101_BUTTON                           0x0A
#define HDLC_BT101_BUTTON_VALUE                     0x0B

/* External Lookup Table Entry */
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table_t;

/* External definitions */
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[];
extern const uint16_t app_gatt_db_ext_attr_tbl_size;
extern uint8_t app_gap_device_name[];
extern const uint16_t app_gap_device_name_len;
extern uint8_t app_gap_appearance[];
extern const uint16_t app_gap_appearance_len;
extern uint8_t app_bt101_led[];
extern const uint16_t app_bt101_led_len;
extern uint8_t app_bt101_button[];
extern const uint16_t app_bt101_button_len;

#endif /* CYCFG_GATT_DB_H */

