/***************************************************************************//**
* File Name: cycfg_gatt_db.c
* Version: 2.20
*
* Description:
* BLE device's GATT database and device configuration.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 2.20.0.3018
*
********************************************************************************
* Copyright 2020 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_gatt_db.h"
#include "wiced_bt_uuid.h"
#include "wiced_bt_gatt.h"

/*************************************************************************************
* GATT server definitions
*************************************************************************************/

const uint8_t gatt_database[] = 
{
    /* Primary Service: Generic Access */
    PRIMARY_SERVICE_UUID16 (HDLS_GAP, __UUID_SERVICE_GENERIC_ACCESS),
        /* Characteristic: Device Name */
        CHARACTERISTIC_UUID16 (HDLC_GAP_DEVICE_NAME, HDLC_GAP_DEVICE_NAME_VALUE, __UUID_CHARACTERISTIC_DEVICE_NAME, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
        /* Characteristic: Appearance */
        CHARACTERISTIC_UUID16 (HDLC_GAP_APPEARANCE, HDLC_GAP_APPEARANCE_VALUE, __UUID_CHARACTERISTIC_APPEARANCE, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),

    /* Primary Service: Generic Attribute */
    PRIMARY_SERVICE_UUID16 (HDLS_GATT, __UUID_SERVICE_GENERIC_ATTRIBUTE),

    /* Primary Service: BT101 */
    PRIMARY_SERVICE_UUID128 (HDLS_BT101, __UUID_SERVICE_BT101),
        /* Characteristic: LED */
        CHARACTERISTIC_UUID128_WRITABLE (HDLC_BT101_LED, HDLC_BT101_LED_VALUE, __UUID_CHARACTERISTIC_BT101_LED, LEGATTDB_CHAR_PROP_READ | LEGATTDB_CHAR_PROP_WRITE, LEGATTDB_PERM_READABLE | LEGATTDB_PERM_WRITE_REQ),
        /* Characteristic: Button */
        CHARACTERISTIC_UUID128 (HDLC_BT101_BUTTON, HDLC_BT101_BUTTON_VALUE, __UUID_CHARACTERISTIC_BT101_BUTTON, LEGATTDB_CHAR_PROP_READ, LEGATTDB_PERM_READABLE),
};

/* Length of the GATT database */
const uint16_t gatt_database_len = sizeof(gatt_database);

/*************************************************************************************
 * GATT Initial Value Arrays
 ************************************************************************************/
 
uint8_t app_gap_device_name[] = {'k', 'e', 'y', '_', 'c', 'o', 'n', };
uint8_t app_gap_appearance[]  = {0x00, 0x00, };
uint8_t app_bt101_led[]       = {0x00, };
uint8_t app_bt101_button[]    = {0x00, };
 
 /************************************************************************************
 * GATT Lookup Table
 ************************************************************************************/
 
gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[] =
{
    /* { attribute handle,  maxlen, curlen, attribute data } */
    { HDLC_GAP_DEVICE_NAME_VALUE, 7,      7,      app_gap_device_name },
    { HDLC_GAP_APPEARANCE_VALUE, 2,      2,      app_gap_appearance },
    { HDLC_BT101_LED_VALUE, 1,      1,      app_bt101_led },
    { HDLC_BT101_BUTTON_VALUE, 1,      1,      app_bt101_button },
};

/* Number of Lookup Table entries */
const uint16_t app_gatt_db_ext_attr_tbl_size = (sizeof(app_gatt_db_ext_attr_tbl) / sizeof(gatt_db_lookup_table_t));

/* Number of GATT initial value arrays entries */
const uint16_t app_gap_device_name_len = (sizeof(app_gap_device_name));
const uint16_t app_gap_appearance_len = (sizeof(app_gap_appearance));
const uint16_t app_bt101_led_len = (sizeof(app_bt101_led));
const uint16_t app_bt101_button_len = (sizeof(app_bt101_button));

