/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * Definitions for constants used in the device's GATT database and function
 * prototypes.
 *
 */

// key_Button_db.h

#ifndef __GATT_DATABASE_H__
#define __GATT_DATABASE_H__

#define __UUID_WICEDBUTTON                        0x1a, 0xa6, 0x06, 0xe0, 0x6f, 0x77, 0x46, 0x55, 0x9a, 0xd1, 0xa1, 0x1d, 0x67, 0xe0, 0xe2, 0xf6
#define __UUID_WICEDBUTTON_MB1                    0x03, 0xaf, 0x38, 0xc9, 0x19, 0x1f, 0x40, 0x5a, 0x91, 0xd5, 0xd4, 0x28, 0xc3, 0xd0, 0xca, 0x03

// ***** Primary Service 'Generic Attribute'
#define HDLS_GENERIC_ATTRIBUTE                    0x0001

// ***** Primary Service 'Generic Access'
#define HDLS_GENERIC_ACCESS                       0x0014
// ----- Characteristic 'Device Name'
#define HDLC_GENERIC_ACCESS_DEVICE_NAME           0x0015
#define HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE     0x0016
// ----- Characteristic 'Appearance'
#define HDLC_GENERIC_ACCESS_APPEARANCE            0x0017
#define HDLC_GENERIC_ACCESS_APPEARANCE_VALUE      0x0018

// ***** Primary Service 'WicedButton'
#define HDLS_WICEDBUTTON                          0x0028
// ----- Characteristic 'MB1'
#define HDLC_WICEDBUTTON_MB1                      0x0029
#define HDLC_WICEDBUTTON_MB1_VALUE                0x002A
// ===== Descriptor 'User Description'
#define HDLD_WICEDBUTTON_MB1_USER_DESCRIPTION     0x002B
// ===== Descriptor 'Client Configuration'
#define HDLD_WICEDBUTTON_MB1_CLIENT_CONFIGURATION 0x002C

// External Lookup Table Entry
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table;

// External definitions
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table key_button_gatt_db_ext_attr_tbl[];
extern const uint16_t key_button_gatt_db_ext_attr_tbl_size;
extern uint8_t BT_LOCAL_NAME[];
extern const uint16_t BT_LOCAL_NAME_CAPACITY;

#endif /* __GATT_DATABASE_H__ */
