#include "wiced.h"
#include "company_ids.h"

typedef struct {
uint16_t companyCode;
char* name;
} company_id_t;

static const company_id_t company_ids[] = {
{.companyCode = 0x0000, .name = "Ericsson Technology Licensing"},
{.companyCode = 0x0001, .name = "Nokia Mobile Phones"},
{.companyCode = 0x0002, .name = "Intel Corp."},
{.companyCode = 0x0003, .name = "IBM Corp."},
{.companyCode = 0x0004, .name = "Toshiba Corp."},
{.companyCode = 0x0005, .name = "3Com"},
{.companyCode = 0x0006, .name = "Microsoft"},
{.companyCode = 0x0007, .name = "Lucent"},
{.companyCode = 0x0008, .name = "Motorola"},
{.companyCode = 0x0009, .name = "Infineon Technologies AG"},
{.companyCode = 0x000A, .name = "Qualcomm Technologies International, Ltd. (QTIL)"},
{.companyCode = 0x000B, .name = "Silicon Wave"},
{.companyCode = 0x000C, .name = "Digianswer A/S"},
{.companyCode = 0x000D, .name = "Texas Instruments Inc."},
{.companyCode = 0x000E, .name = "Parthus Technologies Inc."},
{.companyCode = 0x000F, .name = "Broadcom Corporation"},
{.companyCode = 0x0010, .name = "Mitel Semiconductor"},
{.companyCode = 0x0011, .name = "Widcomm, Inc."},
{.companyCode = 0x0012, .name = "Zeevo, Inc."},
{.companyCode = 0x0013, .name = "Atmel Corporation"},
{.companyCode = 0x0014, .name = "Mitsubishi Electric Corporation"},
{.companyCode = 0x0015, .name = "RTX Telecom A/S"},
{.companyCode = 0x0016, .name = "KC Technology Inc."},
{.companyCode = 0x0017, .name = "Newlogic"},
{.companyCode = 0x0018, .name = "Transilica, Inc."},
{.companyCode = 0x0019, .name = "Rohde & Schwarz GmbH & Co. KG"},
{.companyCode = 0x001A, .name = "TTPCom Limited"},
{.companyCode = 0x001B, .name = "Signia Technologies, Inc."},
{.companyCode = 0x001C, .name = "Conexant Systems Inc."},
{.companyCode = 0x001D, .name = "Qualcomm"},
{.companyCode = 0x001E, .name = "Inventel"},
{.companyCode = 0x001F, .name = "AVM Berlin"},
{.companyCode = 0x0020, .name = "BandSpeed, Inc."},
{.companyCode = 0x0021, .name = "Mansella Ltd"},
{.companyCode = 0x0022, .name = "NEC Corporation"},
{.companyCode = 0x0023, .name = "WavePlus Technology Co., Ltd."},
{.companyCode = 0x0024, .name = "Alcatel"},
{.companyCode = 0x0025, .name = "NXP Semiconductors (formerly Philips Semiconductors)"},
{.companyCode = 0x0026, .name = "C Technologies"},
{.companyCode = 0x0027, .name = "Open Interface"},
{.companyCode = 0x0028, .name = "R F Micro Devices"},
{.companyCode = 0x0029, .name = "Hitachi Ltd"},
{.companyCode = 0x002A, .name = "Symbol Technologies, Inc."},
{.companyCode = 0x002B, .name = "Tenovis"},
{.companyCode = 0x002C, .name = "Macronix International Co. Ltd."},
{.companyCode = 0x002D, .name = "GCT Semiconductor"},
{.companyCode = 0x002E, .name = "Norwood Systems"},
{.companyCode = 0x002F, .name = "MewTel Technology Inc."},
{.companyCode = 0x0030, .name = "ST Microelectronics"},
{.companyCode = 0x0031, .name = "Synopsys, Inc."},
{.companyCode = 0x0032, .name = "Red-M (Communications) Ltd"},
{.companyCode = 0x0033, .name = "Commil Ltd"},
{.companyCode = 0x0034, .name = "Computer Access Technology Corporation (CATC)"},
{.companyCode = 0x0035, .name = "Eclipse (HQ Espana) S.L."},
{.companyCode = 0x0036, .name = "Renesas Electronics Corporation"},
{.companyCode = 0x0037, .name = "Mobilian Corporation"},
{.companyCode = 0x0038, .name = "Syntronix Corporation"},
{.companyCode = 0x0039, .name = "Integrated System Solution Corp."},
{.companyCode = 0x003A, .name = "Matsushita Electric Industrial Co., Ltd."},
{.companyCode = 0x003B, .name = "Gennum Corporation"},
{.companyCode = 0x003C, .name = "BlackBerry Limited  (formerly Research In Motion)"},
{.companyCode = 0x003D, .name = "IPextreme, Inc."},
{.companyCode = 0x003E, .name = "Systems and Chips, Inc"},
{.companyCode = 0x003F, .name = "Bluetooth SIG, Inc"},
{.companyCode = 0x0040, .name = "Seiko Epson Corporation"},
{.companyCode = 0x0041, .name = "Integrated Silicon Solution Taiwan, Inc."},
{.companyCode = 0x0042, .name = "CONWISE Technology Corporation Ltd"},
{.companyCode = 0x0043, .name = "PARROT AUTOMOTIVE SAS"},
{.companyCode = 0x0044, .name = "Socket Mobile"},
{.companyCode = 0x0045, .name = "Atheros Communications, Inc."},
{.companyCode = 0x0046, .name = "MediaTek, Inc."},
{.companyCode = 0x0047, .name = "Bluegiga"},
{.companyCode = 0x0048, .name = "Marvell Technology Group Ltd."},
{.companyCode = 0x0049, .name = "3DSP Corporation"},
{.companyCode = 0x004A, .name = "Accel Semiconductor Ltd."},
{.companyCode = 0x004B, .name = "Continental Automotive Systems"},
{.companyCode = 0x004C, .name = "Apple, Inc."},
{.companyCode = 0x004D, .name = "Staccato Communications, Inc."},
{.companyCode = 0x004E, .name = "Avago Technologies"},
{.companyCode = 0x004F, .name = "APT Ltd."},
{.companyCode = 0x0050, .name = "SiRF Technology, Inc."},
{.companyCode = 0x0051, .name = "Tzero Technologies, Inc."},
{.companyCode = 0x0052, .name = "J&M Corporation"},
{.companyCode = 0x0053, .name = "Free2move AB"},
{.companyCode = 0x0054, .name = "3DiJoy Corporation"},
{.companyCode = 0x0055, .name = "Plantronics, Inc."},
{.companyCode = 0x0056, .name = "Sony Ericsson Mobile Communications"},
{.companyCode = 0x0057, .name = "Harman International Industries, Inc."},
{.companyCode = 0x0058, .name = "Vizio, Inc."},
{.companyCode = 0x0059, .name = "Nordic Semiconductor ASA"},
{.companyCode = 0x005A, .name = "EM Microelectronic-Marin SA"},
{.companyCode = 0x005B, .name = "Ralink Technology Corporation"},
{.companyCode = 0x005C, .name = "Belkin International, Inc. "},
{.companyCode = 0x005D, .name = "Realtek Semiconductor Corporation"},
{.companyCode = 0x005E, .name = "Stonestreet One, LLC"},
{.companyCode = 0x005F, .name = "Wicentric, Inc."},
{.companyCode = 0x0060, .name = "RivieraWaves S.A.S"},
{.companyCode = 0x0061, .name = "RDA Microelectronics"},
{.companyCode = 0x0062, .name = "Gibson Guitars"},
{.companyCode = 0x0063, .name = "MiCommand Inc."},
{.companyCode = 0x0064, .name = "Band XI International, LLC"},
{.companyCode = 0x0065, .name = "Hewlett-Packard Company"},
{.companyCode = 0x0066, .name = "9Solutions Oy"},
{.companyCode = 0x0067, .name = "GN Netcom A/S"},
{.companyCode = 0x0068, .name = "General Motors"},
{.companyCode = 0x0069, .name = "A&D Engineering, Inc."},
{.companyCode = 0x006A, .name = "MindTree Ltd."},
{.companyCode = 0x006B, .name = "Polar Electro OY"},
{.companyCode = 0x006C, .name = "Beautiful Enterprise Co., Ltd."},
{.companyCode = 0x006D, .name = "BriarTek, Inc"},
{.companyCode = 0x006E, .name = "Summit Data Communications, Inc."},
{.companyCode = 0x006F, .name = "Sound ID"},
{.companyCode = 0x0070, .name = "Monster, LLC"},
{.companyCode = 0x0071, .name = "connectBlue AB"},
{.companyCode = 0x0072, .name = "ShangHai Super Smart Electronics Co. Ltd."},
{.companyCode = 0x0073, .name = "Group Sense Ltd. "},
{.companyCode = 0x0074, .name = "Zomm, LLC"},
{.companyCode = 0x0075, .name = "Samsung Electronics Co. Ltd."},
{.companyCode = 0x0076, .name = "Creative Technology Ltd."},
{.companyCode = 0x0077, .name = "Laird Technologies"},
{.companyCode = 0x0078, .name = "Nike, Inc."},
{.companyCode = 0x0079, .name = "lesswire AG"},
{.companyCode = 0x007A, .name = "MStar Semiconductor, Inc."},
{.companyCode = 0x007B, .name = "Hanlynn Technologies"},
{.companyCode = 0x007C, .name = "A & R Cambridge"},
{.companyCode = 0x007D, .name = "Seers Technology Co., Ltd."},
{.companyCode = 0x007E, .name = "Sports Tracking Technologies Ltd."},
{.companyCode = 0x007F, .name = "Autonet Mobile"},
{.companyCode = 0x0080, .name = "DeLorme Publishing Company, Inc."},
{.companyCode = 0x0081, .name = "WuXi Vimicro"},
{.companyCode = 0x0082, .name = "Sennheiser Communications A/S"},
{.companyCode = 0x0083, .name = "TimeKeeping Systems, Inc."},
{.companyCode = 0x0084, .name = "Ludus Helsinki Ltd."},
{.companyCode = 0x0085, .name = "BlueRadios, Inc."},
{.companyCode = 0x0086, .name = "Equinux AG"},
{.companyCode = 0x0087, .name = "Garmin International, Inc."},
{.companyCode = 0x0088, .name = "Ecotest"},
{.companyCode = 0x0089, .name = "GN ReSound A/S"},
{.companyCode = 0x008A, .name = "Jawbone"},
{.companyCode = 0x008B, .name = "Topcon Positioning Systems, LLC"},
{.companyCode = 0x008C, .name = "Gimbal Inc. (formerly Qualcomm Labs, Inc. and Qualcomm Retail Solutions"},
{.companyCode = 0x008D, .name = "Zscan Software"},
{.companyCode = 0x008E, .name = "Quintic Corp"},
{.companyCode = 0x008F, .name = "Telit Wireless Solutions GmbH (formerly Stollmann E+V GmbH)"},
{.companyCode = 0x0090, .name = "Funai Electric Co., Ltd."},
{.companyCode = 0x0091, .name = "Advanced PANMOBIL systems GmbH & Co. KG"},
{.companyCode = 0x0092, .name = "ThinkOptics, Inc. "},
{.companyCode = 0x0093, .name = "Universal Electronics, Inc."},
{.companyCode = 0x0094, .name = "Airoha Technology Corp."},
{.companyCode = 0x0095, .name = "NEC Lighting, Ltd."},
{.companyCode = 0x0096, .name = "ODM Technology, Inc."},
{.companyCode = 0x0097, .name = "ConnecteDevice Ltd."},
{.companyCode = 0x0098, .name = "zero1.tv GmbH"},
{.companyCode = 0x0099, .name = "i.Tech Dynamic Global Distribution Ltd."},
{.companyCode = 0x009A, .name = "Alpwise"},
{.companyCode = 0x009B, .name = "Jiangsu Toppower Automotive Electronics Co., Ltd."},
{.companyCode = 0x009C, .name = "Colorfy, Inc."},
{.companyCode = 0x009D, .name = "Geoforce Inc."},
{.companyCode = 0x009E, .name = "Bose Corporation"},
{.companyCode = 0x009F, .name = "Suunto Oy"},
{.companyCode = 0x00A0, .name = "Kensington Computer Products Group"},
{.companyCode = 0x00A1, .name = "SR-Medizinelektronik"},
{.companyCode = 0x00A2, .name = "Vertu Corporation Limited"},
{.companyCode = 0x00A3, .name = "Meta Watch Ltd."},
{.companyCode = 0x00A4, .name = "LINAK A/S"},
{.companyCode = 0x00A5, .name = "OTL Dynamics LLC"},
{.companyCode = 0x00A6, .name = "Panda Ocean Inc."},
{.companyCode = 0x00A7, .name = "Visteon Corporation"},
{.companyCode = 0x00A8, .name = "ARP Devices Limited"},
{.companyCode = 0x00A9, .name = "Magneti Marelli S.p.A"},
{.companyCode = 0x00AA, .name = "CAEN RFID srl"},
{.companyCode = 0x00AB, .name = "Ingenieur-Systemgruppe Zahn GmbH"},
{.companyCode = 0x00AC, .name = "Green Throttle Games"},
{.companyCode = 0x00AD, .name = "Peter Systemtechnik GmbH"},
{.companyCode = 0x00AE, .name = "Omegawave Oy"},
{.companyCode = 0x00AF, .name = "Cinetix"},
{.companyCode = 0x00B0, .name = "Passif Semiconductor Corp"},
{.companyCode = 0x00B1, .name = "Saris Cycling Group, Inc"},
{.companyCode = 0x00B2, .name = "Bekey A/S"},
{.companyCode = 0x00B3, .name = "Clarinox Technologies Pty. Ltd."},
{.companyCode = 0x00B4, .name = "BDE Technology Co., Ltd."},
{.companyCode = 0x00B5, .name = "Swirl Networks"},
{.companyCode = 0x00B6, .name = "Meso international"},
{.companyCode = 0x00B7, .name = "TreLab Ltd"},
{.companyCode = 0x00B8, .name = "Qualcomm Innovation Center, Inc. (QuIC)"},
{.companyCode = 0x00B9, .name = "Johnson Controls, Inc."},
{.companyCode = 0x00BA, .name = "Starkey Laboratories Inc."},
{.companyCode = 0x00BB, .name = "S-Power Electronics Limited"},
{.companyCode = 0x00BC, .name = "Ace Sensor Inc"},
{.companyCode = 0x00BD, .name = "Aplix Corporation"},
{.companyCode = 0x00BE, .name = "AAMP of America"},
{.companyCode = 0x00BF, .name = "Stalmart Technology Limited"},
{.companyCode = 0x00C0, .name = "AMICCOM Electronics Corporation"},
{.companyCode = 0x00C1, .name = "Shenzhen Excelsecu Data Technology Co.,Ltd"},
{.companyCode = 0x00C2, .name = "Geneq Inc."},
{.companyCode = 0x00C3, .name = "adidas AG"},
{.companyCode = 0x00C4, .name = "LG Electronics"},
{.companyCode = 0x00C5, .name = "Onset Computer Corporation"},
{.companyCode = 0x00C6, .name = "Selfly BV"},
{.companyCode = 0x00C7, .name = "Quuppa Oy."},
{.companyCode = 0x00C8, .name = "GeLo Inc"},
{.companyCode = 0x00C9, .name = "Evluma"},
{.companyCode = 0x00CA, .name = "MC10"},
{.companyCode = 0x00CB, .name = "Binauric SE"},
{.companyCode = 0x00CC, .name = "Beats Electronics"},
{.companyCode = 0x00CD, .name = "Microchip Technology Inc."},
{.companyCode = 0x00CE, .name = "Elgato Systems GmbH"},
{.companyCode = 0x00CF, .name = "ARCHOS SA"},
{.companyCode = 0x00D0, .name = "Dexcom, Inc."},
{.companyCode = 0x00D1, .name = "Polar Electro Europe B.V."},
{.companyCode = 0x00D2, .name = "Dialog Semiconductor B.V."},
{.companyCode = 0x00D3, .name = "Taixingbang Technology (HK) Co,. LTD."},
{.companyCode = 0x00D4, .name = "Kawantech"},
{.companyCode = 0x00D5, .name = "Austco Communication Systems"},
{.companyCode = 0x00D6, .name = "Timex Group USA, Inc."},
{.companyCode = 0x00D7, .name = "Qualcomm Technologies, Inc."},
{.companyCode = 0x00D8, .name = "Qualcomm Connected Experiences, Inc."},
{.companyCode = 0x00D9, .name = "Voyetra Turtle Beach"},
{.companyCode = 0x00DA, .name = "txtr GmbH"},
{.companyCode = 0x00DB, .name = "Biosentronics"},
{.companyCode = 0x00DC, .name = "Procter & Gamble"},
{.companyCode = 0x00DD, .name = "Hosiden Corporation"},
{.companyCode = 0x00DE, .name = "Muzik LLC"},
{.companyCode = 0x00DF, .name = "Misfit Wearables Corp"},
{.companyCode = 0x00E0, .name = "Google"},
{.companyCode = 0x00E1, .name = "Danlers Ltd"},
{.companyCode = 0x00E2, .name = "Semilink Inc"},
{.companyCode = 0x00E3, .name = "inMusic Brands, Inc"},
{.companyCode = 0x00E4, .name = "L.S. Research Inc."},
{.companyCode = 0x00E5, .name = "Eden Software Consultants Ltd."},
{.companyCode = 0x00E6, .name = "Freshtemp"},
{.companyCode = 0x00E7, .name = "KS Technologies"},
{.companyCode = 0x00E8, .name = "ACTS Technologies"},
{.companyCode = 0x00E9, .name = "Vtrack Systems"},
{.companyCode = 0x00EA, .name = "Nielsen-Kellerman Company"},
{.companyCode = 0x00EB, .name = "Server Technology Inc."},
{.companyCode = 0x00EC, .name = "BioResearch Associates"},
{.companyCode = 0x00ED, .name = "Jolly Logic, LLC"},
{.companyCode = 0x00EE, .name = "Above Average Outcomes, Inc."},
{.companyCode = 0x00EF, .name = "Bitsplitters GmbH"},
{.companyCode = 0x00F0, .name = "PayPal, Inc."},
{.companyCode = 0x00F1, .name = "Witron Technology Limited"},
{.companyCode = 0x00F2, .name = "Morse Project Inc."},
{.companyCode = 0x00F3, .name = "Kent Displays Inc."},
{.companyCode = 0x00F4, .name = "Nautilus Inc."},
{.companyCode = 0x00F5, .name = "Smartifier Oy"},
{.companyCode = 0x00F6, .name = "Elcometer Limited"},
{.companyCode = 0x00F7, .name = "VSN Technologies, Inc."},
{.companyCode = 0x00F8, .name = "AceUni Corp., Ltd."},
{.companyCode = 0x00F9, .name = "StickNFind"},
{.companyCode = 0x00FA, .name = "Crystal Code AB"},
{.companyCode = 0x00FB, .name = "KOUKAAM a.s."},
{.companyCode = 0x00FC, .name = "Delphi Corporation"},
{.companyCode = 0x00FD, .name = "ValenceTech Limited"},
{.companyCode = 0x00FE, .name = "Stanley Black and Decker"},
{.companyCode = 0x00FF, .name = "Typo Products, LLC"},
{.companyCode = 0x0100, .name = "TomTom International BV"},
{.companyCode = 0x0101, .name = "Fugoo, Inc."},
{.companyCode = 0x0102, .name = "Keiser Corporation"},
{.companyCode = 0x0103, .name = "Bang & Olufsen A/S"},
{.companyCode = 0x0104, .name = "PLUS Location Systems Pty Ltd"},
{.companyCode = 0x0105, .name = "Ubiquitous Computing Technology Corporation"},
{.companyCode = 0x0106, .name = "Innovative Yachtter Solutions"},
{.companyCode = 0x0107, .name = "William Demant Holding A/S"},
{.companyCode = 0x0108, .name = "Chicony Electronics Co., Ltd."},
{.companyCode = 0x0109, .name = "Atus BV"},
{.companyCode = 0x010A, .name = "Codegate Ltd"},
{.companyCode = 0x010B, .name = "ERi, Inc"},
{.companyCode = 0x010C, .name = "Transducers Direct, LLC"},
{.companyCode = 0x010D, .name = "Fujitsu Ten LImited"},
{.companyCode = 0x010E, .name = "Audi AG"},
{.companyCode = 0x010F, .name = "HiSilicon Technologies Col, Ltd."},
{.companyCode = 0x0110, .name = "Nippon Seiki Co., Ltd."},
{.companyCode = 0x0111, .name = "Steelseries ApS"},
{.companyCode = 0x0112, .name = "Visybl Inc."},
{.companyCode = 0x0113, .name = "Openbrain Technologies, Co."},
{.companyCode = 0x0114, .name = "Xensr"},
{.companyCode = 0x0115, .name = "e.solutions"},
{.companyCode = 0x0116, .name = "10AK Technologies"},
{.companyCode = 0x0117, .name = "Wimoto Technologies Inc"},
{.companyCode = 0x0118, .name = "Radius Networks, Inc."},
{.companyCode = 0x0119, .name = "Wize Technology Co., Ltd."},
{.companyCode = 0x011A, .name = "Qualcomm Labs, Inc."},
{.companyCode = 0x011B, .name = "Hewlett Packard Enterprise"},
{.companyCode = 0x011C, .name = "Baidu"},
{.companyCode = 0x011D, .name = "Arendi AG"},
{.companyCode = 0x011E, .name = "Skoda Auto a.s."},
{.companyCode = 0x011F, .name = "Volkswagen AG"},
{.companyCode = 0x0120, .name = "Porsche AG"},
{.companyCode = 0x0121, .name = "Sino Wealth Electronic Ltd."},
{.companyCode = 0x0122, .name = "AirTurn, Inc."},
{.companyCode = 0x0123, .name = "Kinsa, Inc"},
{.companyCode = 0x0124, .name = "HID Global"},
{.companyCode = 0x0125, .name = "SEAT es"},
{.companyCode = 0x0126, .name = "Promethean Ltd."},
{.companyCode = 0x0127, .name = "Salutica Allied Solutions"},
{.companyCode = 0x0128, .name = "GPSI Group Pty Ltd"},
{.companyCode = 0x0129, .name = "Nimble Devices Oy"},
{.companyCode = 0x012A, .name = "Changzhou Yongse Infotech  Co., Ltd."},
{.companyCode = 0x012B, .name = "SportIQ"},
{.companyCode = 0x012C, .name = "TEMEC Instruments B.V."},
{.companyCode = 0x012D, .name = "Sony Corporation"},
{.companyCode = 0x012E, .name = "ASSA ABLOY"},
{.companyCode = 0x012F, .name = "Clarion Co. Inc."},
{.companyCode = 0x0130, .name = "Warehouse Innovations"},
{.companyCode = 0x0131, .name = "Cypress Semiconductor"},
{.companyCode = 0x0132, .name = "MADS Inc"},
{.companyCode = 0x0133, .name = "Blue Maestro Limited"},
{.companyCode = 0x0134, .name = "Resolution Products, Ltd."},
{.companyCode = 0x0135, .name = "Aireware LLC"},
{.companyCode = 0x0136, .name = "Silvair, Inc."},
{.companyCode = 0x0137, .name = "Prestigio Plaza Ltd."},
{.companyCode = 0x0138, .name = "NTEO Inc."},
{.companyCode = 0x0139, .name = "Focus Systems Corporation"},
{.companyCode = 0x013A, .name = "Tencent Holdings Ltd."},
{.companyCode = 0x013B, .name = "Allegion"},
{.companyCode = 0x013C, .name = "Murata Manufacturing Co., Ltd. "},
{.companyCode = 0x013D, .name = "WirelessWERX"},
{.companyCode = 0x013E, .name = "Nod, Inc."},
{.companyCode = 0x013F, .name = "B&B Manufacturing Company"},
{.companyCode = 0x0140, .name = "Alpine Electronics (China) Co., Ltd"},
{.companyCode = 0x0141, .name = "FedEx Services"},
{.companyCode = 0x0142, .name = "Grape Systems Inc."},
{.companyCode = 0x0143, .name = "Bkon Connect"},
{.companyCode = 0x0144, .name = "Lintech GmbH"},
{.companyCode = 0x0145, .name = "Novatel Wireless"},
{.companyCode = 0x0146, .name = "Ciright"},
{.companyCode = 0x0147, .name = "Mighty Cast, Inc."},
{.companyCode = 0x0148, .name = "Ambimat Electronics"},
{.companyCode = 0x0149, .name = "Perytons Ltd."},
{.companyCode = 0x014A, .name = "Tivoli Audio, LLC"},
{.companyCode = 0x014B, .name = "Master Lock"},
{.companyCode = 0x014C, .name = "Mesh-Net Ltd"},
{.companyCode = 0x014D, .name = "HUIZHOU DESAY SV AUTOMOTIVE CO., LTD."},
{.companyCode = 0x014E, .name = "Tangerine, Inc."},
{.companyCode = 0x014F, .name = "B&W Group Ltd."},
{.companyCode = 0x0150, .name = "Pioneer Corporation"},
{.companyCode = 0x0151, .name = "OnBeep"},
{.companyCode = 0x0152, .name = "Vernier Software & Technology"},
{.companyCode = 0x0153, .name = "ROL Ergo"},
{.companyCode = 0x0154, .name = "Pebble Technology"},
{.companyCode = 0x0155, .name = "NETATMO"},
{.companyCode = 0x0156, .name = "Accumulate AB"},
{.companyCode = 0x0157, .name = "Anhui Huami Information Technology Co., Ltd."},
{.companyCode = 0x0158, .name = "Inmite s.r.o."},
{.companyCode = 0x0159, .name = "ChefSteps, Inc."},
{.companyCode = 0x015A, .name = "micas AG"},
{.companyCode = 0x015B, .name = "Biomedical Research Ltd."},
{.companyCode = 0x015C, .name = "Pitius Tec S.L."},
{.companyCode = 0x015D, .name = "Estimote, Inc."},
{.companyCode = 0x015E, .name = "Unikey Technologies, Inc."},
{.companyCode = 0x015F, .name = "Timer Cap Co."},
{.companyCode = 0x0160, .name = "AwoX"},
{.companyCode = 0x0161, .name = "yikes"},
{.companyCode = 0x0162, .name = "MADSGlobalNZ Ltd."},
{.companyCode = 0x0163, .name = "PCH International"},
{.companyCode = 0x0164, .name = "Qingdao Yeelink Information Technology Co., Ltd."},
{.companyCode = 0x0165, .name = "Milwaukee Tool (Formally Milwaukee Electric Tools) "},
{.companyCode = 0x0166, .name = "MISHIK Pte Ltd"},
{.companyCode = 0x0167, .name = "Ascensia Diabetes Care US Inc."},
{.companyCode = 0x0168, .name = "Spicebox LLC"},
{.companyCode = 0x0169, .name = "emberlight"},
{.companyCode = 0x016A, .name = "Cooper-Atkins Corporation"},
{.companyCode = 0x016B, .name = "Qblinks"},
{.companyCode = 0x016C, .name = "MYSPHERA"},
{.companyCode = 0x016D, .name = "LifeScan Inc"},
{.companyCode = 0x016E, .name = "Volantic AB"},
{.companyCode = 0x016F, .name = "Podo Labs, Inc"},
{.companyCode = 0x0170, .name = "Roche Diabetes Care AG"},
{.companyCode = 0x0171, .name = "Amazon Fulfillment Service"},
{.companyCode = 0x0172, .name = "Connovate Technology Private Limited"},
{.companyCode = 0x0173, .name = "Kocomojo, LLC"},
{.companyCode = 0x0174, .name = "Everykey Inc. "},
{.companyCode = 0x0175, .name = "Dynamic Controls"},
{.companyCode = 0x0176, .name = "SentriLock"},
{.companyCode = 0x0177, .name = "I-SYST inc."},
{.companyCode = 0x0178, .name = "CASIO COMPUTER CO., LTD."},
{.companyCode = 0x0179, .name = "LAPIS Semiconductor Co., Ltd."},
{.companyCode = 0x017A, .name = "Telemonitor, Inc."},
{.companyCode = 0x017B, .name = "taskit GmbH"},
{.companyCode = 0x017C, .name = "Daimler AG"},
{.companyCode = 0x017D, .name = "BatAndCat"},
{.companyCode = 0x017E, .name = "BluDotz Ltd"},
{.companyCode = 0x017F, .name = "XTel Wireless ApS"},
{.companyCode = 0x0180, .name = "Gigaset Communications GmbH"},
{.companyCode = 0x0181, .name = "Gecko Health Innovations, Inc."},
{.companyCode = 0x0182, .name = "HOP Ubiquitous"},
{.companyCode = 0x0183, .name = "Walt Disney"},
{.companyCode = 0x0184, .name = "Nectar"},
{.companyCode = 0x0185, .name = "bel&#39;apps LLC"},
{.companyCode = 0x0186, .name = "CORE Lighting Ltd"},
{.companyCode = 0x0187, .name = "Seraphim Sense Ltd"},
{.companyCode = 0x0188, .name = "Unico RBC "},
{.companyCode = 0x0189, .name = "Physical Enterprises Inc."},
{.companyCode = 0x018A, .name = "Able Trend Technology Limited"},
{.companyCode = 0x018B, .name = "Konica Minolta, Inc."},
{.companyCode = 0x018C, .name = "Wilo SE"},
{.companyCode = 0x018D, .name = "Extron Design Services"},
{.companyCode = 0x018E, .name = "Fitbit, Inc."},
{.companyCode = 0x018F, .name = "Fireflies Systems"},
{.companyCode = 0x0190, .name = "Intelletto Technologies Inc."},
{.companyCode = 0x0191, .name = "FDK CORPORATION "},
{.companyCode = 0x0192, .name = "Cloudleaf, Inc"},
{.companyCode = 0x0193, .name = "Maveric Automation LLC"},
{.companyCode = 0x0194, .name = "Acoustic Stream Corporation"},
{.companyCode = 0x0195, .name = "Zuli"},
{.companyCode = 0x0196, .name = "Paxton Access Ltd"},
{.companyCode = 0x0197, .name = "WiSilica Inc."},
{.companyCode = 0x0198, .name = "VENGIT Korlatolt Felelossegu Tarsasag"},
{.companyCode = 0x0199, .name = "SALTO SYSTEMS S.L."},
{.companyCode = 0x019A, .name = "TRON Forum (formerly T-Engine Forum)"},
{.companyCode = 0x019B, .name = "CUBETECH s.r.o."},
{.companyCode = 0x019C, .name = "Cokiya Incorporated"},
{.companyCode = 0x019D, .name = "CVS Health"},
{.companyCode = 0x019E, .name = "Ceruus"},
{.companyCode = 0x019F, .name = "Strainstall Ltd"},
{.companyCode = 0x01A0, .name = "Channel Enterprises (HK) Ltd."},
{.companyCode = 0x01A1, .name = "FIAMM"},
{.companyCode = 0x01A2, .name = "GIGALANE.CO.,LTD"},
{.companyCode = 0x01A3, .name = "EROAD"},
{.companyCode = 0x01A4, .name = "Mine Safety Appliances"},
{.companyCode = 0x01A5, .name = "Icon Health and Fitness"},
{.companyCode = 0x01A6, .name = "Asandoo GmbH"},
{.companyCode = 0x01A7, .name = "ENERGOUS CORPORATION"},
{.companyCode = 0x01A8, .name = "Taobao"},
{.companyCode = 0x01A9, .name = "Canon Inc."},
{.companyCode = 0x01AA, .name = "Geophysical Technology Inc."},
{.companyCode = 0x01AB, .name = "Facebook, Inc."},
{.companyCode = 0x01AC, .name = "Trividia Health, Inc."},
{.companyCode = 0x01AD, .name = "FlightSafety International"},
{.companyCode = 0x01AE, .name = "Earlens Corporation"},
{.companyCode = 0x01AF, .name = "Sunrise Micro Devices, Inc."},
{.companyCode = 0x01B0, .name = "Star Micronics Co., Ltd."},
{.companyCode = 0x01B1, .name = "Netizens Sp. z o.o."},
{.companyCode = 0x01B2, .name = "Nymi Inc."},
{.companyCode = 0x01B3, .name = "Nytec, Inc."},
{.companyCode = 0x01B4, .name = "Trineo Sp. z o.o."},
{.companyCode = 0x01B5, .name = "Nest Labs Inc."},
{.companyCode = 0x01B6, .name = "LM Technologies Ltd"},
{.companyCode = 0x01B7, .name = "General Electric Company"},
{.companyCode = 0x01B8, .name = "i+D3 S.L."},
{.companyCode = 0x01B9, .name = "HANA Micron"},
{.companyCode = 0x01BA, .name = "Stages Cycling LLC"},
{.companyCode = 0x01BB, .name = "Cochlear Bone Anchored Solutions AB"},
{.companyCode = 0x01BC, .name = "SenionLab AB"},
{.companyCode = 0x01BD, .name = "Syszone Co., Ltd"},
{.companyCode = 0x01BE, .name = "Pulsate Mobile Ltd."},
{.companyCode = 0x01BF, .name = "Hong Kong HunterSun Electronic Limited"},
{.companyCode = 0x01C0, .name = "pironex GmbH"},
{.companyCode = 0x01C1, .name = "BRADATECH Corp."},
{.companyCode = 0x01C2, .name = "Transenergooil AG"},
{.companyCode = 0x01C3, .name = "Bunch"},
{.companyCode = 0x01C4, .name = "DME Microelectronics"},
{.companyCode = 0x01C5, .name = "Bitcraze AB"},
{.companyCode = 0x01C6, .name = "HASWARE Inc."},
{.companyCode = 0x01C7, .name = "Abiogenix Inc."},
{.companyCode = 0x01C8, .name = "Poly-Control ApS"},
{.companyCode = 0x01C9, .name = "Avi-on"},
{.companyCode = 0x01CA, .name = "Laerdal Medical AS"},
{.companyCode = 0x01CB, .name = "Fetch My Pet"},
{.companyCode = 0x01CC, .name = "Sam Labs Ltd."},
{.companyCode = 0x01CD, .name = "Chengdu Synwing Technology Ltd"},
{.companyCode = 0x01CE, .name = "HOUWA SYSTEM DESIGN, k.k."},
{.companyCode = 0x01CF, .name = "BSH"},
{.companyCode = 0x01D0, .name = "Primus Inter Pares Ltd"},
{.companyCode = 0x01D1, .name = "August Home, Inc"},
{.companyCode = 0x01D2, .name = "Gill Electronics"},
{.companyCode = 0x01D3, .name = "Sky Wave Design"},
{.companyCode = 0x01D4, .name = "Newlab S.r.l."},
{.companyCode = 0x01D5, .name = "ELAD srl"},
{.companyCode = 0x01D6, .name = "G-wearables inc."},
{.companyCode = 0x01D7, .name = "Squadrone Systems Inc."},
{.companyCode = 0x01D8, .name = "Code Corporation"},
{.companyCode = 0x01D9, .name = "Savant Systems LLC"},
{.companyCode = 0x01DA, .name = "Logitech International SA"},
{.companyCode = 0x01DB, .name = "Innblue Consulting"},
{.companyCode = 0x01DC, .name = "iParking Ltd."},
{.companyCode = 0x01DD, .name = "Koninklijke Philips Electronics N.V."},
{.companyCode = 0x01DE, .name = "Minelab Electronics Pty Limited"},
{.companyCode = 0x01DF, .name = "Bison Group Ltd."},
{.companyCode = 0x01E0, .name = "Widex A/S"},
{.companyCode = 0x01E1, .name = "Jolla Ltd"},
{.companyCode = 0x01E2, .name = "Lectronix, Inc."},
{.companyCode = 0x01E3, .name = "Caterpillar Inc"},
{.companyCode = 0x01E4, .name = "Freedom Innovations"},
{.companyCode = 0x01E5, .name = "Dynamic Devices Ltd"},
{.companyCode = 0x01E6, .name = "Technology Solutions (UK) Ltd"},
{.companyCode = 0x01E7, .name = "IPS Group Inc."},
{.companyCode = 0x01E8, .name = "STIR"},
{.companyCode = 0x01E9, .name = "Sano, Inc."},
{.companyCode = 0x01EA, .name = "Advanced Application Design, Inc."},
{.companyCode = 0x01EB, .name = "AutoMap LLC"},
{.companyCode = 0x01EC, .name = "Spreadtrum Communications Shanghai Ltd"},
{.companyCode = 0x01ED, .name = "CuteCircuit LTD"},
{.companyCode = 0x01EE, .name = "Valeo Service"},
{.companyCode = 0x01EF, .name = "Fullpower Technologies, Inc. "},
{.companyCode = 0x01F0, .name = "KloudNation"},
{.companyCode = 0x01F1, .name = "Zebra Technologies Corporation"},
{.companyCode = 0x01F2, .name = "Itron, Inc. "},
{.companyCode = 0x01F3, .name = "The University of Tokyo"},
{.companyCode = 0x01F4, .name = "UTC Fire and Security"},
{.companyCode = 0x01F5, .name = "Cool Webthings Limited"},
{.companyCode = 0x01F6, .name = "DJO Global"},
{.companyCode = 0x01F7, .name = "Gelliner Limited"},
{.companyCode = 0x01F8, .name = "Anyka (Guangzhou) Microelectronics Technology Co, LTD "},
{.companyCode = 0x01F9, .name = "Medtronic Inc."},
{.companyCode = 0x01FA, .name = "Gozio Inc."},
{.companyCode = 0x01FB, .name = "Form Lifting, LLC"},
{.companyCode = 0x01FC, .name = "Wahoo Fitness, LLC"},
{.companyCode = 0x01FD, .name = "Kontakt Micro-Location Sp. z o.o. "},
{.companyCode = 0x01FE, .name = "Radio Systems Corporation"},
{.companyCode = 0x01FF, .name = "Freescale Semiconductor, Inc."},
{.companyCode = 0x0200, .name = "Verifone Systems Pte Ltd. Taiwan Branch"},
{.companyCode = 0x0201, .name = "AR Timing"},
{.companyCode = 0x0202, .name = "Rigado LLC"},
{.companyCode = 0x0203, .name = "Kemppi Oy"},
{.companyCode = 0x0204, .name = "Tapcentive Inc."},
{.companyCode = 0x0205, .name = "Smartbotics Inc."},
{.companyCode = 0x0206, .name = "Otter Products, LLC"},
{.companyCode = 0x0207, .name = "STEMP Inc."},
{.companyCode = 0x0208, .name = "LumiGeek LLC"},
{.companyCode = 0x0209, .name = "InvisionHeart Inc."},
{.companyCode = 0x020A, .name = "Macnica Inc. "},
{.companyCode = 0x020B, .name = "Jaguar Land Rover Limited"},
{.companyCode = 0x020C, .name = "CoroWare Technologies, Inc"},
{.companyCode = 0x020D, .name = "Simplo Technology Co., LTD"},
{.companyCode = 0x020E, .name = "Omron Healthcare Co., LTD"},
{.companyCode = 0x020F, .name = "Comodule GMBH"},
{.companyCode = 0x0210, .name = "ikeGPS"},
{.companyCode = 0x0211, .name = "Telink Semiconductor Co. Ltd"},
{.companyCode = 0x0212, .name = "Interplan Co., Ltd"},
{.companyCode = 0x0213, .name = "Wyler AG"},
{.companyCode = 0x0214, .name = "IK Multimedia Production srl"},
{.companyCode = 0x0215, .name = "Lukoton Experience Oy"},
{.companyCode = 0x0216, .name = "MTI Ltd"},
{.companyCode = 0x0217, .name = "Tech4home, Lda"},
{.companyCode = 0x0218, .name = "Hiotech AB"},
{.companyCode = 0x0219, .name = "DOTT Limited"},
{.companyCode = 0x021A, .name = "Blue Speck Labs, LLC"},
{.companyCode = 0x021B, .name = "Cisco Systems, Inc"},
{.companyCode = 0x021C, .name = "Mobicomm Inc"},
{.companyCode = 0x021D, .name = "Edamic"},
{.companyCode = 0x021E, .name = "Goodnet, Ltd"},
{.companyCode = 0x021F, .name = "Luster Leaf Products  Inc"},
{.companyCode = 0x0220, .name = "Manus Machina BV"},
{.companyCode = 0x0221, .name = "Mobiquity Networks Inc"},
{.companyCode = 0x0222, .name = "Praxis Dynamics"},
{.companyCode = 0x0223, .name = "Philip Morris Products S.A."},
{.companyCode = 0x0224, .name = "Comarch SA"},
{.companyCode = 0x0225, .name = "Nestl Nespresso S.A."},
{.companyCode = 0x0226, .name = "Merlinia A/S"},
{.companyCode = 0x0227, .name = "LifeBEAM Technologies"},
{.companyCode = 0x0228, .name = "Twocanoes Labs, LLC"},
{.companyCode = 0x0229, .name = "Muoverti Limited"},
{.companyCode = 0x022A, .name = "Stamer Musikanlagen GMBH"},
{.companyCode = 0x022B, .name = "Tesla Motors"},
{.companyCode = 0x022C, .name = "Pharynks Corporation"},
{.companyCode = 0x022D, .name = "Lupine"},
{.companyCode = 0x022E, .name = "Siemens AG"},
{.companyCode = 0x022F, .name = "Huami (Shanghai) Culture Communication CO., LTD"},
{.companyCode = 0x0230, .name = "Foster Electric Company, Ltd"},
{.companyCode = 0x0231, .name = "ETA SA"},
{.companyCode = 0x0232, .name = "x-Senso Solutions Kft"},
{.companyCode = 0x0233, .name = "Shenzhen SuLong Communication Ltd"},
{.companyCode = 0x0234, .name = "FengFan (BeiJing) Technology Co, Ltd"},
{.companyCode = 0x0235, .name = "Qrio Inc"},
{.companyCode = 0x0236, .name = "Pitpatpet Ltd"},
{.companyCode = 0x0237, .name = "MSHeli s.r.l."},
{.companyCode = 0x0238, .name = "Trakm8 Ltd"},
{.companyCode = 0x0239, .name = "JIN CO, Ltd "},
{.companyCode = 0x023A, .name = "Alatech Tehnology"},
{.companyCode = 0x023B, .name = "Beijing CarePulse Electronic Technology Co, Ltd"},
{.companyCode = 0x023C, .name = "Awarepoint"},
{.companyCode = 0x023D, .name = "ViCentra B.V."},
{.companyCode = 0x023E, .name = "Raven Industries"},
{.companyCode = 0x023F, .name = "WaveWare Technologies Inc."},
{.companyCode = 0x0240, .name = "Argenox Technologies"},
{.companyCode = 0x0241, .name = "Bragi GmbH"},
{.companyCode = 0x0242, .name = "16Lab Inc"},
{.companyCode = 0x0243, .name = "Masimo Corp"},
{.companyCode = 0x0244, .name = "Iotera Inc"},
{.companyCode = 0x0245, .name = "Endress+Hauser"},
{.companyCode = 0x0246, .name = "ACKme Networks, Inc."},
{.companyCode = 0x0247, .name = "FiftyThree Inc."},
{.companyCode = 0x0248, .name = "Parker Hannifin Corp"},
{.companyCode = 0x0249, .name = "Transcranial Ltd"},
{.companyCode = 0x024A, .name = "Uwatec AG"},
{.companyCode = 0x024B, .name = "Orlan LLC"},
{.companyCode = 0x024C, .name = "Blue Clover Devices"},
{.companyCode = 0x024D, .name = "M-Way Solutions GmbH"},
{.companyCode = 0x024E, .name = "Microtronics Engineering GmbH"},
{.companyCode = 0x024F, .name = "Schneider Schreibgerte GmbH"},
{.companyCode = 0x0250, .name = "Sapphire Circuits LLC"},
{.companyCode = 0x0251, .name = "Lumo Bodytech Inc."},
{.companyCode = 0x0252, .name = "UKC Technosolution"},
{.companyCode = 0x0253, .name = "Xicato Inc."},
{.companyCode = 0x0254, .name = "Playbrush"},
{.companyCode = 0x0255, .name = "Dai Nippon Printing Co., Ltd."},
{.companyCode = 0x0256, .name = "G24 Power Limited"},
{.companyCode = 0x0257, .name = "AdBabble Local Commerce Inc."},
{.companyCode = 0x0258, .name = "Devialet SA"},
{.companyCode = 0x0259, .name = "ALTYOR"},
{.companyCode = 0x025A, .name = "University of Applied Sciences Valais/Haute Ecole Valaisanne"},
{.companyCode = 0x025B, .name = "Five Interactive, LLC dba Zendo"},
{.companyCode = 0x025C, .name = "NetEaseHangzhouNetwork co.Ltd."},
{.companyCode = 0x025D, .name = "Lexmark International Inc."},
{.companyCode = 0x025E, .name = "Fluke Corporation"},
{.companyCode = 0x025F, .name = "Yardarm Technologies"},
{.companyCode = 0x0260, .name = "SensaRx"},
{.companyCode = 0x0261, .name = "SECVRE GmbH"},
{.companyCode = 0x0262, .name = "Glacial Ridge Technologies"},
{.companyCode = 0x0263, .name = "Identiv, Inc."},
{.companyCode = 0x0264, .name = "DDS, Inc."},
{.companyCode = 0x0265, .name = "SMK Corporation"},
{.companyCode = 0x0266, .name = "Schawbel Technologies LLC"},
{.companyCode = 0x0267, .name = "XMI Systems SA"},
{.companyCode = 0x0268, .name = "Cerevo"},
{.companyCode = 0x0269, .name = "Torrox GmbH & Co KG"},
{.companyCode = 0x026A, .name = "Gemalto"},
{.companyCode = 0x026B, .name = "DEKA Research & Development Corp."},
{.companyCode = 0x026C, .name = "Domster Tadeusz Szydlowski"},
{.companyCode = 0x026D, .name = "Technogym SPA"},
{.companyCode = 0x026E, .name = "FLEURBAEY BVBA"},
{.companyCode = 0x026F, .name = "Aptcode Solutions"},
{.companyCode = 0x0270, .name = "LSI ADL Technology"},
{.companyCode = 0x0271, .name = "Animas Corp"},
{.companyCode = 0x0272, .name = "Alps Electric Co., Ltd."},
{.companyCode = 0x0273, .name = "OCEASOFT"},
{.companyCode = 0x0274, .name = "Motsai Research"},
{.companyCode = 0x0275, .name = "Geotab"},
{.companyCode = 0x0276, .name = "E.G.O. Elektro-Gertebau GmbH"},
{.companyCode = 0x0277, .name = "bewhere inc"},
{.companyCode = 0x0278, .name = "Johnson Outdoors Inc"},
{.companyCode = 0x0279, .name = "steute Schaltgerate GmbH & Co. KG"},
{.companyCode = 0x027A, .name = "Ekomini inc."},
{.companyCode = 0x027B, .name = "DEFA AS"},
{.companyCode = 0x027C, .name = "Aseptika Ltd"},
{.companyCode = 0x027D, .name = "HUAWEI Technologies Co., Ltd. (  )"},
{.companyCode = 0x027E, .name = "HabitAware, LLC"},
{.companyCode = 0x027F, .name = "ruwido austria gmbh"},
{.companyCode = 0x0280, .name = "ITEC corporation"},
{.companyCode = 0x0281, .name = "StoneL"},
{.companyCode = 0x0282, .name = "Sonova AG"},
{.companyCode = 0x0283, .name = "Maven Machines, Inc."},
{.companyCode = 0x0284, .name = "Synapse Electronics"},
{.companyCode = 0x0285, .name = "Standard Innovation Inc."},
{.companyCode = 0x0286, .name = "RF Code, Inc."},
{.companyCode = 0x0287, .name = "Wally Ventures S.L."},
{.companyCode = 0x0288, .name = "Willowbank Electronics Ltd"},
{.companyCode = 0x0289, .name = "SK Telecom"},
{.companyCode = 0x028A, .name = "Jetro AS"},
{.companyCode = 0x028B, .name = "Code Gears LTD"},
{.companyCode = 0x028C, .name = "NANOLINK APS"},
{.companyCode = 0x028D, .name = "IF, LLC"},
{.companyCode = 0x028E, .name = "RF Digital Corp"},
{.companyCode = 0x028F, .name = "Church & Dwight Co., Inc"},
{.companyCode = 0x0290, .name = "Multibit Oy"},
{.companyCode = 0x0291, .name = "CliniCloud Inc"},
{.companyCode = 0x0292, .name = "SwiftSensors"},
{.companyCode = 0x0293, .name = "Blue Bite"},
{.companyCode = 0x0294, .name = "ELIAS GmbH"},
{.companyCode = 0x0295, .name = "Sivantos GmbH"},
{.companyCode = 0x0296, .name = "Petzl"},
{.companyCode = 0x0297, .name = "storm power ltd"},
{.companyCode = 0x0298, .name = "EISST Ltd"},
{.companyCode = 0x0299, .name = "Inexess Technology Simma KG"},
{.companyCode = 0x029A, .name = "Currant, Inc."},
{.companyCode = 0x029B, .name = "C2 Development, Inc."},
{.companyCode = 0x029C, .name = "Blue Sky Scientific, LLC"},
{.companyCode = 0x029D, .name = "ALOTTAZS LABS, LLC"},
{.companyCode = 0x029E, .name = "Kupson spol. s r.o."},
{.companyCode = 0x029F, .name = "Areus Engineering GmbH"},
{.companyCode = 0x02A0, .name = "Impossible Camera GmbH"},
{.companyCode = 0x02A1, .name = "InventureTrack Systems"},
{.companyCode = 0x02A2, .name = "LockedUp"},
{.companyCode = 0x02A3, .name = "Itude"},
{.companyCode = 0x02A4, .name = "Pacific Lock Company"},
{.companyCode = 0x02A5, .name = "Tendyron Corporation (  )"},
{.companyCode = 0x02A6, .name = "Robert Bosch GmbH"},
{.companyCode = 0x02A7, .name = "Illuxtron international B.V."},
{.companyCode = 0x02A8, .name = "miSport Ltd."},
{.companyCode = 0x02A9, .name = "Chargelib"},
{.companyCode = 0x02AA, .name = "Doppler Lab"},
{.companyCode = 0x02AB, .name = "BBPOS Limited"},
{.companyCode = 0x02AC, .name = "RTB Elektronik GmbH & Co. KG"},
{.companyCode = 0x02AD, .name = "Rx Networks, Inc."},
{.companyCode = 0x02AE, .name = "WeatherFlow, Inc."},
{.companyCode = 0x02AF, .name = "Technicolor USA Inc."},
{.companyCode = 0x02B0, .name = "Bestechnic(Shanghai),Ltd"},
{.companyCode = 0x02B1, .name = "Raden Inc"},
{.companyCode = 0x02B2, .name = "JouZen Oy"},
{.companyCode = 0x02B3, .name = "CLABER S.P.A."},
{.companyCode = 0x02B4, .name = "Hyginex, Inc."},
{.companyCode = 0x02B5, .name = "HANSHIN ELECTRIC RAILWAY CO.,LTD."},
{.companyCode = 0x02B6, .name = "Schneider Electric"},
{.companyCode = 0x02B7, .name = "Oort Technologies LLC"},
{.companyCode = 0x02B8, .name = "Chrono Therapeutics"},
{.companyCode = 0x02B9, .name = "Rinnai Corporation"},
{.companyCode = 0x02BA, .name = "Swissprime Technologies AG"},
{.companyCode = 0x02BB, .name = "Koha.,Co.Ltd"},
{.companyCode = 0x02BC, .name = "Genevac Ltd"},
{.companyCode = 0x02BD, .name = "Chemtronics"},
{.companyCode = 0x02BE, .name = "Seguro Technology Sp. z o.o."},
{.companyCode = 0x02BF, .name = "Redbird Flight Simulations"},
{.companyCode = 0x02C0, .name = "Dash Robotics"},
{.companyCode = 0x02C1, .name = "LINE Corporation"},
{.companyCode = 0x02C2, .name = "Guillemot Corporation"},
{.companyCode = 0x02C3, .name = "Techtronic Power Tools Technology Limited"},
{.companyCode = 0x02C4, .name = "Wilson Sporting Goods"},
{.companyCode = 0x02C5, .name = "Lenovo (Singapore) Pte Ltd. (  )"},
{.companyCode = 0x02C6, .name = "Ayatan Sensors"},
{.companyCode = 0x02C7, .name = "Electronics Tomorrow Limited"},
{.companyCode = 0x02C8, .name = "VASCO Data Security International, Inc."},
{.companyCode = 0x02C9, .name = "PayRange Inc."},
{.companyCode = 0x02CA, .name = "ABOV Semiconductor"},
{.companyCode = 0x02CB, .name = "AINA-Wireless Inc."},
{.companyCode = 0x02CC, .name = "Eijkelkamp Soil & Water"},
{.companyCode = 0x02CD, .name = "BMA ergonomics b.v."},
{.companyCode = 0x02CE, .name = "Teva Branded Pharmaceutical Products R&D, Inc."},
{.companyCode = 0x02CF, .name = "Anima"},
{.companyCode = 0x02D0, .name = "3M"},
{.companyCode = 0x02D1, .name = "Empatica Srl"},
{.companyCode = 0x02D2, .name = "Afero, Inc."},
{.companyCode = 0x02D3, .name = "Powercast Corporation"},
{.companyCode = 0x02D4, .name = "Secuyou ApS"},
{.companyCode = 0x02D5, .name = "OMRON Corporation"},
{.companyCode = 0x02D6, .name = "Send Solutions"},
{.companyCode = 0x02D7, .name = "NIPPON SYSTEMWARE CO.,LTD."},
{.companyCode = 0x02D8, .name = "Neosfar"},
{.companyCode = 0x02D9, .name = "Fliegl Agrartechnik GmbH"},
{.companyCode = 0x02DA, .name = "Gilvader"},
{.companyCode = 0x02DB, .name = "Digi International Inc (R)"},
{.companyCode = 0x02DC, .name = "DeWalch Technologies, Inc."},
{.companyCode = 0x02DD, .name = "Flint Rehabilitation Devices, LLC"},
{.companyCode = 0x02DE, .name = "Samsung SDS Co., Ltd."},
{.companyCode = 0x02DF, .name = "Blur Product Development"},
{.companyCode = 0x02E0, .name = "University of Michigan"},
{.companyCode = 0x02E1, .name = "Victron Energy BV"},
{.companyCode = 0x02E2, .name = "NTT docomo"},
{.companyCode = 0x02E3, .name = "Carmanah Technologies Corp."},
{.companyCode = 0x02E4, .name = "Bytestorm Ltd."},
{.companyCode = 0x02E5, .name = "Espressif Incorporated ( () )"},
{.companyCode = 0x02E6, .name = "Unwire"},
{.companyCode = 0x02E7, .name = "Connected Yard, Inc."},
{.companyCode = 0x02E8, .name = "American Music Environments"},
{.companyCode = 0x02E9, .name = "Sensogram Technologies, Inc."},
{.companyCode = 0x02EA, .name = "Fujitsu Limited"},
{.companyCode = 0x02EB, .name = "Ardic Technology"},
{.companyCode = 0x02EC, .name = "Delta Systems, Inc"},
{.companyCode = 0x02ED, .name = "HTC Corporation"},
{.companyCode = 0x02EE, .name = "Citizen Holdings Co., Ltd."},
{.companyCode = 0x02EF, .name = "SMART-INNOVATION.inc"},
{.companyCode = 0x02F0, .name = "Blackrat Software"},
{.companyCode = 0x02F1, .name = "The Idea Cave, LLC"},
{.companyCode = 0x02F2, .name = "GoPro, Inc."},
{.companyCode = 0x02F3, .name = "AuthAir, Inc"},
{.companyCode = 0x02F4, .name = "Vensi, Inc."},
{.companyCode = 0x02F5, .name = "Indagem Tech LLC"},
{.companyCode = 0x02F6, .name = "Intemo Technologies"},
{.companyCode = 0x02F7, .name = "DreamVisions co., Ltd."},
{.companyCode = 0x02F8, .name = "Runteq Oy Ltd"},
{.companyCode = 0x02F9, .name = "IMAGINATION TECHNOLOGIES LTD"},
{.companyCode = 0x02FA, .name = "CoSTAR TEchnologies"},
{.companyCode = 0x02FB, .name = "Clarius Mobile Health Corp."},
{.companyCode = 0x02FC, .name = "Shanghai Frequen Microelectronics Co., Ltd."},
{.companyCode = 0x02FD, .name = "Uwanna, Inc."},
{.companyCode = 0x02FE, .name = "Lierda Science & Technology Group Co., Ltd."},
{.companyCode = 0x02FF, .name = "Silicon Laboratories"},
{.companyCode = 0x0300, .name = "World Moto Inc."},
{.companyCode = 0x0301, .name = "Giatec Scientific Inc."},
{.companyCode = 0x0302, .name = "Loop Devices, Inc"},
{.companyCode = 0x0303, .name = "IACA electronique"},
{.companyCode = 0x0304, .name = "Proxy Technologies, Inc."},
{.companyCode = 0x0305, .name = "Swipp ApS"},
{.companyCode = 0x0306, .name = "Life Laboratory Inc."},
{.companyCode = 0x0307, .name = "FUJI INDUSTRIAL CO.,LTD. "},
{.companyCode = 0x0308, .name = "Surefire, LLC"},
{.companyCode = 0x0309, .name = "Dolby Labs"},
{.companyCode = 0x030A, .name = "Ellisys"},
{.companyCode = 0x030B, .name = "Magnitude Lighting Converters"},
{.companyCode = 0x030C, .name = "Hilti AG"},
{.companyCode = 0x030D, .name = "Devdata S.r.l."},
{.companyCode = 0x030E, .name = "Deviceworx"},
{.companyCode = 0x030F, .name = "Shortcut Labs"},
{.companyCode = 0x0310, .name = "SGL Italia S.r.l."},
{.companyCode = 0x0311, .name = "PEEQ DATA"},
{.companyCode = 0x0312, .name = "Ducere Technologies Pvt Ltd"},
{.companyCode = 0x0313, .name = "DiveNav, Inc."},
{.companyCode = 0x0314, .name = "RIIG AI Sp. z o.o."},
{.companyCode = 0x0315, .name = "Thermo Fisher Scientific"},
{.companyCode = 0x0316, .name = "AG Measurematics Pvt. Ltd."},
{.companyCode = 0x0317, .name = "CHUO Electronics CO., LTD."},
{.companyCode = 0x0318, .name = "Aspenta International"},
{.companyCode = 0x0319, .name = "Eugster Frismag AG"},
{.companyCode = 0x031A, .name = "Amber wireless GmbH"},
{.companyCode = 0x031B, .name = "HQ Inc"},
{.companyCode = 0x031C, .name = "Lab Sensor Solutions"},
{.companyCode = 0x031D, .name = "Enterlab ApS"},
{.companyCode = 0x031E, .name = "Eyefi, Inc."},
{.companyCode = 0x031F, .name = "MetaSystem S.p.A."},
{.companyCode = 0x0320, .name = "SONO ELECTRONICS. CO., LTD"},
{.companyCode = 0x0321, .name = "Jewelbots"},
{.companyCode = 0x0322, .name = "Compumedics Limited"},
{.companyCode = 0x0323, .name = "Rotor Bike Components"},
{.companyCode = 0x0324, .name = "Astro, Inc."},
{.companyCode = 0x0325, .name = "Amotus Solutions"},
{.companyCode = 0x0326, .name = "Healthwear Technologies (Changzhou)Ltd"},
{.companyCode = 0x0327, .name = "Essex Electronics"},
{.companyCode = 0x0328, .name = "Grundfos A/S"},
{.companyCode = 0x0329, .name = "Eargo, Inc."},
{.companyCode = 0x032A, .name = "Electronic Design Lab"},
{.companyCode = 0x032B, .name = "ESYLUX"},
{.companyCode = 0x032C, .name = "NIPPON SMT.CO.,Ltd"},
{.companyCode = 0x032D, .name = "BM innovations GmbH"},
{.companyCode = 0x032E, .name = "indoormap"},
{.companyCode = 0x032F, .name = "OttoQ Inc"},
{.companyCode = 0x0330, .name = "North Pole Engineering"},
{.companyCode = 0x0331, .name = "3flares Technologies Inc."},
{.companyCode = 0x0332, .name = "Electrocompaniet A.S."},
{.companyCode = 0x0333, .name = "Mul-T-Lock"},
{.companyCode = 0x0334, .name = "Corentium AS"},
{.companyCode = 0x0335, .name = "Enlighted Inc"},
{.companyCode = 0x0336, .name = "GISTIC"},
{.companyCode = 0x0337, .name = "AJP2 Holdings, LLC"},
{.companyCode = 0x0338, .name = "COBI GmbH"},
{.companyCode = 0x0339, .name = "Blue Sky Scientific, LLC"},
{.companyCode = 0x033A, .name = "Appception, Inc."},
{.companyCode = 0x033B, .name = "Courtney Thorne Limited"},
{.companyCode = 0x033C, .name = "Virtuosys"},
{.companyCode = 0x033D, .name = "TPV Technology Limited"},
{.companyCode = 0x033E, .name = "Monitra SA"},
{.companyCode = 0x033F, .name = "Automation Components, Inc."},
{.companyCode = 0x0340, .name = "Letsense s.r.l."},
{.companyCode = 0x0341, .name = "Etesian Technologies LLC"},
{.companyCode = 0x0342, .name = "GERTEC BRASIL LTDA."},
{.companyCode = 0x0343, .name = "Drekker Development Pty. Ltd."},
{.companyCode = 0x0344, .name = "Whirl Inc"},
{.companyCode = 0x0345, .name = "Locus Positioning"},
{.companyCode = 0x0346, .name = "Acuity Brands Lighting, Inc"},
{.companyCode = 0x0347, .name = "Prevent Biometrics"},
{.companyCode = 0x0348, .name = "Arioneo"},
{.companyCode = 0x0349, .name = "VersaMe"},
{.companyCode = 0x034A, .name = "Vaddio"},
{.companyCode = 0x034B, .name = "Libratone A/S"},
{.companyCode = 0x034C, .name = "HM Electronics, Inc."},
{.companyCode = 0x034D, .name = "TASER International, Inc."},
{.companyCode = 0x034E, .name = "SafeTrust Inc."},
{.companyCode = 0x034F, .name = "Heartland Payment Systems"},
{.companyCode = 0x0350, .name = "Bitstrata Systems Inc."},
{.companyCode = 0x0351, .name = "Pieps GmbH"},
{.companyCode = 0x0352, .name = "iRiding(Xiamen)Technology Co.,Ltd."},
{.companyCode = 0x0353, .name = "Alpha Audiotronics, Inc."},
{.companyCode = 0x0354, .name = "TOPPAN FORMS CO.,LTD."},
{.companyCode = 0x0355, .name = "Sigma Designs, Inc."},
{.companyCode = 0x0356, .name = "Spectrum Brands, Inc."},
{.companyCode = 0x0357, .name = "Polymap Wireless"},
{.companyCode = 0x0358, .name = "MagniWare Ltd. "},
{.companyCode = 0x0359, .name = "Novotec Medical GmbH"},
{.companyCode = 0x035A, .name = "Medicom Innovation Partner a/s"},
{.companyCode = 0x035B, .name = "Matrix Inc."},
{.companyCode = 0x035C, .name = "Eaton Corporation"},
{.companyCode = 0x035D, .name = "KYS"},
{.companyCode = 0x035E, .name = "Naya Health, Inc."},
{.companyCode = 0x035F, .name = "Acromag"},
{.companyCode = 0x0360, .name = "Insulet Corporation"},
{.companyCode = 0x0361, .name = "Wellinks Inc."},
{.companyCode = 0x0362, .name = "ON Semiconductor"},
{.companyCode = 0x0363, .name = "FREELAP SA"},
{.companyCode = 0x0364, .name = "Favero Electronics Srl"},
{.companyCode = 0x0365, .name = "BioMech Sensor LLC"},
{.companyCode = 0x0366, .name = "BOLTT Sports technologies Private limited"},
{.companyCode = 0x0367, .name = "Saphe International"},
{.companyCode = 0x0368, .name = "Metormote AB"},
{.companyCode = 0x0369, .name = "littleBits"},
{.companyCode = 0x036A, .name = "SetPoint Medical"},
{.companyCode = 0x036B, .name = "BRControls Products BV"},
{.companyCode = 0x036C, .name = "Zipcar"},
{.companyCode = 0x036D, .name = "AirBolt Pty Ltd"},
{.companyCode = 0x036E, .name = "KeepTruckin Inc"},
{.companyCode = 0x036F, .name = "Motiv, Inc."},
{.companyCode = 0x0370, .name = "Wazombi Labs O"},
{.companyCode = 0x0371, .name = "ORBCOMM"},
{.companyCode = 0x0372, .name = "Nixie Labs, Inc."},
{.companyCode = 0x0373, .name = "AppNearMe Ltd"},
{.companyCode = 0x0374, .name = "Holman Industries"},
{.companyCode = 0x0375, .name = "Expain AS"},
{.companyCode = 0x0376, .name = "Electronic Temperature Instruments Ltd"},
{.companyCode = 0x0377, .name = "Plejd AB"},
{.companyCode = 0x0378, .name = "Propeller Health"},
{.companyCode = 0x0379, .name = "Shenzhen iMCO Electronic Technology Co.,Ltd"},
{.companyCode = 0x037A, .name = "Algoria"},
{.companyCode = 0x037B, .name = "Apption Labs Inc."},
{.companyCode = 0x037C, .name = "Cronologics Corporation"},
{.companyCode = 0x037D, .name = "MICRODIA Ltd."},
{.companyCode = 0x037E, .name = "lulabytes S.L."},
{.companyCode = 0x037F, .name = "Nestec S.A."},
{.companyCode = 0x0380, .name = "LLC &quot;MEGA-F service&quot;"},
{.companyCode = 0x0381, .name = "Sharp Corporation"},
{.companyCode = 0x0382, .name = "Precision Outcomes Ltd"},
{.companyCode = 0x0383, .name = "Kronos Incorporated"},
{.companyCode = 0x0384, .name = "OCOSMOS Co., Ltd."},
{.companyCode = 0x0385, .name = "Embedded Electronic Solutions Ltd. dba e2Solutions"},
{.companyCode = 0x0386, .name = "Aterica Inc."},
{.companyCode = 0x0387, .name = "BluStor PMC, Inc."},
{.companyCode = 0x0388, .name = "Kapsch TrafficCom AB"},
{.companyCode = 0x0389, .name = "ActiveBlu Corporation"},
{.companyCode = 0x038A, .name = "Kohler Mira Limited"},
{.companyCode = 0x038B, .name = "Noke"},
{.companyCode = 0x038C, .name = "Appion Inc."},
{.companyCode = 0x038D, .name = "Resmed Ltd"},
{.companyCode = 0x038E, .name = "Crownstone B.V."},
{.companyCode = 0x038F, .name = "Xiaomi Inc."},
{.companyCode = 0x0390, .name = "INFOTECH s.r.o."},
{.companyCode = 0x0391, .name = "Thingsquare AB"},
{.companyCode = 0x0392, .name = "T&D"},
{.companyCode = 0x0393, .name = "LAVAZZA S.p.A."},
{.companyCode = 0x0394, .name = "Netclearance Systems, Inc."},
{.companyCode = 0x0395, .name = "SDATAWAY"},
{.companyCode = 0x0396, .name = "BLOKS GmbH"},
{.companyCode = 0x0397, .name = "LEGO System A/S"},
{.companyCode = 0x0398, .name = "Thetatronics Ltd"},
{.companyCode = 0x0399, .name = "Nikon Corporation"},
{.companyCode = 0x039A, .name = "NeST"},
{.companyCode = 0x039B, .name = "South Silicon Valley Microelectronics"},
{.companyCode = 0x039C, .name = "ALE International"},
{.companyCode = 0x039D, .name = "CareView Communications, Inc."},
{.companyCode = 0x039E, .name = "SchoolBoard Limited"},
{.companyCode = 0x039F, .name = "Molex Corporation"},
{.companyCode = 0x03A0, .name = "IVT Wireless Limited"},
{.companyCode = 0x03A1, .name = "Alpine Labs LLC"},
{.companyCode = 0x03A2, .name = "Candura Instruments"},
{.companyCode = 0x03A3, .name = "SmartMovt Technology Co., Ltd"},
{.companyCode = 0x03A4, .name = "Token Zero Ltd"},
{.companyCode = 0x03A5, .name = "ACE CAD Enterprise Co., Ltd. (ACECAD)"},
{.companyCode = 0x03A6, .name = "Medela, Inc"},
{.companyCode = 0x03A7, .name = "AeroScout"},
{.companyCode = 0x03A8, .name = "Esrille Inc."},
{.companyCode = 0x03A9, .name = "THINKERLY SRL"},
{.companyCode = 0x03AA, .name = "Exon Sp. z o.o."},
{.companyCode = 0x03AB, .name = "Meizu Technology Co., Ltd."},
{.companyCode = 0x03AC, .name = "Smablo LTD"},
{.companyCode = 0x03AD, .name = "XiQ"},
{.companyCode = 0x03AE, .name = "Allswell Inc."},
{.companyCode = 0x03AF, .name = "Comm-N-Sense Corp DBA Verigo"},
{.companyCode = 0x03B0, .name = "VIBRADORM GmbH"},
{.companyCode = 0x03B1, .name = "Otodata Wireless Network Inc."},
{.companyCode = 0x03B2, .name = "Propagation Systems Limited"},
{.companyCode = 0x03B3, .name = "Midwest Instruments & Controls"},
{.companyCode = 0x03B4, .name = "Alpha Nodus, inc."},
{.companyCode = 0x03B5, .name = "petPOMM, Inc"},
{.companyCode = 0x03B6, .name = "Mattel"},
{.companyCode = 0x03B7, .name = "Airbly Inc."},
{.companyCode = 0x03B8, .name = "A-Safe Limited"},
{.companyCode = 0x03B9, .name = "FREDERIQUE CONSTANT SA"},
{.companyCode = 0x03BA, .name = "Maxscend Microelectronics Company Limited"},
{.companyCode = 0x03BB, .name = "Abbott Diabetes Care"},
{.companyCode = 0x03BC, .name = "ASB Bank Ltd"},
{.companyCode = 0x03BD, .name = "amadas"},
{.companyCode = 0x03BE, .name = "Applied Science, Inc."},
{.companyCode = 0x03BF, .name = "iLumi Solutions Inc."},
{.companyCode = 0x03C0, .name = "Arch Systems Inc."},
{.companyCode = 0x03C1, .name = "Ember Technologies, Inc."},
{.companyCode = 0x03C2, .name = "Snapchat Inc"},
{.companyCode = 0x03C3, .name = "Casambi Technologies Oy"},
{.companyCode = 0x03C4, .name = "Pico Technology Inc."},
{.companyCode = 0x03C5, .name = "St. Jude Medical, Inc."},
{.companyCode = 0x03C6, .name = "Intricon"},
{.companyCode = 0x03C7, .name = "Structural Health Systems, Inc."},
{.companyCode = 0x03C8, .name = "Avvel International"},
{.companyCode = 0x03C9, .name = "Gallagher Group"},
{.companyCode = 0x03CA, .name = "In2things Automation Pvt. Ltd."},
{.companyCode = 0x03CB, .name = "SYSDEV Srl"},
{.companyCode = 0x03CC, .name = "Vonkil Technologies Ltd"},
{.companyCode = 0x03CD, .name = "Wynd Technologies, Inc."},
{.companyCode = 0x03CE, .name = "CONTRINEX S.A."},
{.companyCode = 0x03CF, .name = "MIRA, Inc."},
{.companyCode = 0x03D0, .name = "Watteam Ltd"},
{.companyCode = 0x03D1, .name = "Density Inc."},
{.companyCode = 0x03D2, .name = "IOT Pot India Private Limited"},
{.companyCode = 0x03D3, .name = "Sigma Connectivity AB"},
{.companyCode = 0x03D4, .name = "PEG PEREGO SPA"},
{.companyCode = 0x03D5, .name = "Wyzelink Systems Inc."},
{.companyCode = 0x03D6, .name = "Yota Devices LTD"},
{.companyCode = 0x03D7, .name = "FINSECUR"},
{.companyCode = 0x03D8, .name = "Zen-Me Labs Ltd"},
{.companyCode = 0x03D9, .name = "3IWare Co., Ltd."},
{.companyCode = 0x03DA, .name = "EnOcean GmbH"},
{.companyCode = 0x03DB, .name = "Instabeat, Inc"},
{.companyCode = 0x03DC, .name = "Nima Labs"},
{.companyCode = 0x03DD, .name = "Andreas Stihl AG & Co. KG"},
{.companyCode = 0x03DE, .name = "Nathan Rhoades LLC"},
{.companyCode = 0x03DF, .name = "Grob Technologies, LLC"},
{.companyCode = 0x03E0, .name = "Actions (Zhuhai) Technology Co., Limited"},
{.companyCode = 0x03E1, .name = "SPD Development Company Ltd"},
{.companyCode = 0x03E2, .name = "Sensoan Oy"},
{.companyCode = 0x03E3, .name = "Qualcomm Life Inc"},
{.companyCode = 0x03E4, .name = "Chip-ing AG"},
{.companyCode = 0x03E5, .name = "ffly4u"},
{.companyCode = 0x03E6, .name = "IoT Instruments Oy"},
{.companyCode = 0x03E7, .name = "TRUE Fitness Technology"},
{.companyCode = 0x03E8, .name = "Reiner Kartengeraete GmbH & Co. KG."},
{.companyCode = 0x03E9, .name = "SHENZHEN LEMONJOY TECHNOLOGY CO., LTD."},
{.companyCode = 0x03EA, .name = "Hello Inc."},
{.companyCode = 0x03EB, .name = "Evollve Inc."},
{.companyCode = 0x03EC, .name = "Jigowatts Inc."},
{.companyCode = 0x03ED, .name = "BASIC MICRO.COM,INC."},
{.companyCode = 0x03EE, .name = "CUBE TECHNOLOGIES"},
{.companyCode = 0x03EF, .name = "foolography GmbH"},
{.companyCode = 0x03F0, .name = "CLINK"},
{.companyCode = 0x03F1, .name = "Hestan Smart Cooking Inc."},
{.companyCode = 0x03F2, .name = "WindowMaster A/S"},
{.companyCode = 0x03F3, .name = "Flowscape AB"},
{.companyCode = 0x03F4, .name = "PAL Technologies Ltd"},
{.companyCode = 0x03F5, .name = "WHERE, Inc."},
{.companyCode = 0x03F6, .name = "Iton Technology Corp."},
{.companyCode = 0x03F7, .name = "Owl Labs Inc."},
{.companyCode = 0x03F8, .name = "Rockford Corp."},
{.companyCode = 0x03F9, .name = "Becon Technologies Co.,Ltd."},
{.companyCode = 0x03FA, .name = "Vyassoft Technologies Inc"},
{.companyCode = 0x03FB, .name = "Nox Medical"},
{.companyCode = 0x03FC, .name = "Kimberly-Clark"},
{.companyCode = 0x03FD, .name = "Trimble Navigation Ltd."},
{.companyCode = 0x03FE, .name = "Littelfuse"},
{.companyCode = 0x03FF, .name = "Withings"},
{.companyCode = 0x0400, .name = "i-developer IT Beratung UG"},
{.companyCode = 0x0401, .name = ""},
{.companyCode = 0x0402, .name = "Sears Holdings Corporation"},
{.companyCode = 0x0403, .name = "Gantner Electronic GmbH"},
{.companyCode = 0x0404, .name = "Authomate Inc"},
{.companyCode = 0x0405, .name = "Vertex International, Inc."},
{.companyCode = 0x0406, .name = "Airtago"},
{.companyCode = 0x0407, .name = "Swiss Audio SA"},
{.companyCode = 0x0408, .name = "ToGetHome Inc."},
{.companyCode = 0x0409, .name = "AXIS"},
{.companyCode = 0x040A, .name = "Openmatics"},
{.companyCode = 0x040B, .name = "Jana Care Inc."},
{.companyCode = 0x040C, .name = "Senix Corporation"},
{.companyCode = 0x040D, .name = "NorthStar Battery Company, LLC"},
{.companyCode = 0x040E, .name = "SKF (U.K.) Limited"},
{.companyCode = 0x040F, .name = "CO-AX Technology, Inc."},
{.companyCode = 0x0410, .name = "Fender Musical Instruments"},
{.companyCode = 0x0411, .name = "Luidia Inc"},
{.companyCode = 0x0412, .name = "SEFAM"},
{.companyCode = 0x0413, .name = "Wireless Cables Inc"},
{.companyCode = 0x0414, .name = "Lightning Protection International Pty Ltd"},
{.companyCode = 0x0415, .name = "Uber Technologies Inc"},
{.companyCode = 0x0416, .name = "SODA GmbH"},
{.companyCode = 0x0417, .name = "Fatigue Science"},
{.companyCode = 0x0418, .name = "Alpine Electronics Inc."},
{.companyCode = 0x0419, .name = "Novalogy LTD"},
{.companyCode = 0x041A, .name = "Friday Labs Limited"},
{.companyCode = 0x041B, .name = "OrthoAccel Technologies"},
{.companyCode = 0x041C, .name = "WaterGuru, Inc."},
{.companyCode = 0x041D, .name = "Benning Elektrotechnik und Elektronik GmbH & Co. KG"},
{.companyCode = 0x041E, .name = "Dell Computer Corporation"},
{.companyCode = 0x041F, .name = "Kopin Corporation"},
{.companyCode = 0x0420, .name = "TecBakery GmbH"},
{.companyCode = 0x0421, .name = "Backbone Labs, Inc."},
{.companyCode = 0x0422, .name = "DELSEY SA"},
{.companyCode = 0x0423, .name = "Chargifi Limited"},
{.companyCode = 0x0424, .name = "Trainesense Ltd."},
{.companyCode = 0x0425, .name = "Unify Software and Solutions GmbH & Co. KG"},
{.companyCode = 0x0426, .name = "Husqvarna AB"},
{.companyCode = 0x0427, .name = "Focus fleet and fuel management inc"},
{.companyCode = 0x0428, .name = "SmallLoop, LLC"},
{.companyCode = 0x0429, .name = "Prolon Inc."},
{.companyCode = 0x042A, .name = "BD Medical"},
{.companyCode = 0x042B, .name = "iMicroMed Incorporated"},
{.companyCode = 0x042C, .name = "Ticto N.V."},
{.companyCode = 0x042D, .name = "Meshtech AS"},
{.companyCode = 0x042E, .name = "MemCachier Inc."},
{.companyCode = 0x042F, .name = "Danfoss A/S"},
{.companyCode = 0x0430, .name = "SnapStyk Inc."},
{.companyCode = 0x0431, .name = "Amway Corporation"},
{.companyCode = 0x0432, .name = "Silk Labs, Inc."},
{.companyCode = 0x0433, .name = "Pillsy Inc."},
{.companyCode = 0x0434, .name = "Hatch Baby, Inc."},
{.companyCode = 0x0435, .name = "Blocks Wearables Ltd."},
{.companyCode = 0x0436, .name = "Drayson Technologies (Europe) Limited"},
{.companyCode = 0x0437, .name = "eBest IOT Inc."},
{.companyCode = 0x0438, .name = "Helvar Ltd"},
{.companyCode = 0x0439, .name = "Radiance Technologies"},
{.companyCode = 0x043A, .name = "Nuheara Limited"},
{.companyCode = 0x043B, .name = "Appside co., ltd."},
{.companyCode = 0x043C, .name = "DeLaval"},
{.companyCode = 0x043D, .name = "Coiler Corporation"},
{.companyCode = 0x043E, .name = "Thermomedics, Inc."},
{.companyCode = 0x043F, .name = "Tentacle Sync GmbH"},
{.companyCode = 0x0440, .name = "Valencell, Inc."},
{.companyCode = 0x0441, .name = "iProtoXi Oy"},
{.companyCode = 0x0442, .name = "SECOM CO., LTD."},
{.companyCode = 0x0443, .name = "Tucker International LLC"},
{.companyCode = 0x0444, .name = "Metanate Limited"},
{.companyCode = 0x0445, .name = "Kobian Canada Inc."},
{.companyCode = 0x0446, .name = "NETGEAR, Inc."},
{.companyCode = 0x0447, .name = "Fabtronics Australia Pty Ltd"},
{.companyCode = 0x0448, .name = "Grand Centrix GmbH"},
{.companyCode = 0x0449, .name = "1UP USA.com llc"},
{.companyCode = 0x044A, .name = "SHIMANO INC."},
{.companyCode = 0x044B, .name = "Nain Inc."},
{.companyCode = 0x044C, .name = "LifeStyle Lock, LLC"},
{.companyCode = 0x044D, .name = "VEGA Grieshaber KG"},
{.companyCode = 0x044E, .name = "Xtrava Inc."},
{.companyCode = 0x044F, .name = "TTS Tooltechnic Systems AG & Co. KG"},
{.companyCode = 0x0450, .name = "Teenage Engineering AB"},
{.companyCode = 0x0451, .name = "Tunstall Nordic AB"},
{.companyCode = 0x0452, .name = "Svep Design Center AB"},
{.companyCode = 0x0453, .name = "GreenPeak Technologies BV"},
{.companyCode = 0x0454, .name = "Sphinx Electronics GmbH & Co KG"},
{.companyCode = 0x0455, .name = "Atomation"},
{.companyCode = 0x0456, .name = "Nemik Consulting Inc "},
{.companyCode = 0x0457, .name = "RF INNOVATION"},
{.companyCode = 0x0458, .name = "Mini Solution Co., Ltd."},
{.companyCode = 0x0459, .name = "Lumenetix, Inc"},
{.companyCode = 0x045A, .name = "2048450 Ontario Inc"},
{.companyCode = 0x045B, .name = "SPACEEK LTD"},
{.companyCode = 0x045C, .name = "Delta T Corporation"},
{.companyCode = 0x045D, .name = "Boston Scientific Corporation"},
{.companyCode = 0x045E, .name = "Nuviz, Inc."},
{.companyCode = 0x045F, .name = "Real Time Automation, Inc."},
{.companyCode = 0x0460, .name = "Kolibree"},
{.companyCode = 0x0461, .name = "vhf elektronik GmbH"},
{.companyCode = 0x0462, .name = "Bonsai Systems GmbH"},
{.companyCode = 0x0463, .name = "Fathom Systems Inc."},
{.companyCode = 0x0464, .name = "Bellman & Symfon"},
{.companyCode = 0x0465, .name = "International Forte Group LLC"},
{.companyCode = 0x0466, .name = "CycleLabs Solutions inc."},
{.companyCode = 0x0467, .name = "Codenex Oy"},
{.companyCode = 0x0468, .name = "Kynesim Ltd"},
{.companyCode = 0x0469, .name = "Palago AB"},
{.companyCode = 0x046A, .name = "INSIGMA INC."},
{.companyCode = 0x046B, .name = "PMD Solutions"},
{.companyCode = 0x046C, .name = "Qingdao Realtime Technology Co., Ltd."},
{.companyCode = 0x046D, .name = "BEGA Gantenbrink-Leuchten KG"},
{.companyCode = 0x046E, .name = "Pambor Ltd."},
{.companyCode = 0x046F, .name = "Develco Products A/S"},
{.companyCode = 0x0470, .name = "iDesign s.r.l."},
{.companyCode = 0x0471, .name = "TiVo Corp"},
{.companyCode = 0x0472, .name = "Control-J Pty Ltd"},
{.companyCode = 0x0473, .name = "Steelcase, Inc."},
{.companyCode = 0x0474, .name = "iApartment co., ltd."},
{.companyCode = 0x0475, .name = "Icom inc."},
{.companyCode = 0x0476, .name = "Oxstren Wearable Technologies Private Limited"},
{.companyCode = 0x0477, .name = "Blue Spark Technologies"},
{.companyCode = 0x0478, .name = "FarSite Communications Limited"},
{.companyCode = 0x0479, .name = "mywerk system GmbH"},
{.companyCode = 0x047A, .name = "Sinosun Technology Co., Ltd."},
{.companyCode = 0x047B, .name = "MIYOSHI ELECTRONICS CORPORATION"},
{.companyCode = 0x047C, .name = "POWERMAT LTD"},
{.companyCode = 0x047D, .name = "Occly LLC"},
{.companyCode = 0x047E, .name = "OurHub Dev IvS"},
{.companyCode = 0x047F, .name = "Pro-Mark, Inc."},
{.companyCode = 0x0480, .name = "Dynometrics Inc."},
{.companyCode = 0x0481, .name = "Quintrax Limited"},
{.companyCode = 0x0482, .name = "POS Tuning Udo Vosshenrich GmbH & Co. KG"},
{.companyCode = 0x0483, .name = "Multi Care Systems B.V."},
{.companyCode = 0x0484, .name = "Revol Technologies Inc"},
{.companyCode = 0x0485, .name = "SKIDATA AG"},
{.companyCode = 0x0486, .name = "DEV TECNOLOGIA INDUSTRIA, COMERCIO E MANUTENCAO DE EQUIPAMENTOS LTDA. - ME"},
{.companyCode = 0x0487, .name = "Centrica Connected Home"},
{.companyCode = 0x0488, .name = "Automotive Data Solutions Inc"},
{.companyCode = 0x0489, .name = "Igarashi Engineering"},
{.companyCode = 0x048A, .name = "Taelek Oy"},
{.companyCode = 0x048B, .name = "CP Electronics Limited"},
{.companyCode = 0x048C, .name = "Vectronix AG"},
{.companyCode = 0x048D, .name = "S-Labs Sp. z o.o."},
{.companyCode = 0x048E, .name = "Companion Medical, Inc."},
{.companyCode = 0x048F, .name = "BlueKitchen GmbH"},
{.companyCode = 0x0490, .name = "Matting AB"},
{.companyCode = 0x0491, .name = "SOREX - Wireless Solutions GmbH"},
{.companyCode = 0x0492, .name = "ADC Technology, Inc."},
{.companyCode = 0x0493, .name = "Lynxemi Pte Ltd"},
{.companyCode = 0x0494, .name = "SENNHEISER electronic GmbH & Co. KG"},
{.companyCode = 0x0495, .name = "LMT Mercer Group, Inc"},
{.companyCode = 0x0496, .name = "Polymorphic Labs LLC"},
{.companyCode = 0x0497, .name = "Cochlear Limited"},
{.companyCode = 0x0498, .name = "METER Group, Inc. USA"},
{.companyCode = 0x0499, .name = "Ruuvi Innovations Ltd."},
{.companyCode = 0x049A, .name = "Situne AS"},
{.companyCode = 0x049B, .name = "nVisti, LLC"},
{.companyCode = 0x049C, .name = "DyOcean"},
{.companyCode = 0x049D, .name = "Uhlmann & Zacher GmbH"},
{.companyCode = 0x049E, .name = "AND!XOR LLC"},
{.companyCode = 0x049F, .name = "tictote AB"},
{.companyCode = 0x04A0, .name = "Vypin, LLC"},
{.companyCode = 0x04A1, .name = "PNI Sensor Corporation"},
{.companyCode = 0x04A2, .name = "ovrEngineered, LLC"},
{.companyCode = 0x04A3, .name = "GT-tronics HK Ltd"},
{.companyCode = 0x04A4, .name = "Herbert Waldmann GmbH & Co. KG"},
{.companyCode = 0x04A5, .name = "Guangzhou FiiO Electronics Technology Co.,Ltd"},
{.companyCode = 0x04A6, .name = "Vinetech Co., Ltd"},
{.companyCode = 0x04A7, .name = "Dallas Logic Corporation"},
{.companyCode = 0x04A8, .name = "BioTex, Inc."},
{.companyCode = 0x04A9, .name = "DISCOVERY SOUND TECHNOLOGY, LLC"},
{.companyCode = 0x04AA, .name = "LINKIO SAS"},
{.companyCode = 0x04AB, .name = "Harbortronics, Inc."},
{.companyCode = 0x04AC, .name = "Undagrid B.V."},
{.companyCode = 0x04AD, .name = "Shure Inc"},
{.companyCode = 0x04AE, .name = "ERM Electronic Systems LTD"},
{.companyCode = 0x04AF, .name = "BIOROWER Handelsagentur GmbH"},
{.companyCode = 0x04B0, .name = "Weba Sport und Med. Artikel GmbH"},
{.companyCode = 0x04B1, .name = "Kartographers Technologies Pvt. Ltd."},
{.companyCode = 0x04B2, .name = "The Shadow on the Moon"},
{.companyCode = 0x04B3, .name = "mobike (Hong Kong) Limited"},
{.companyCode = 0x04B4, .name = "Inuheat Group AB"},
{.companyCode = 0x04B5, .name = "Swiftronix AB"},
{.companyCode = 0x04B6, .name = "Diagnoptics Technologies"},
{.companyCode = 0x04B7, .name = "Analog Devices, Inc."},
{.companyCode = 0x04B8, .name = "Soraa Inc."},
{.companyCode = 0x04B9, .name = "CSR Building Products Limited"},
{.companyCode = 0x04BA, .name = "Crestron Electronics, Inc."},
{.companyCode = 0x04BB, .name = "Neatebox Ltd"},
{.companyCode = 0x04BC, .name = "Draegerwerk AG & Co. KGaA"},
{.companyCode = 0x04BD, .name = "AlbynMedical"},
{.companyCode = 0x04BE, .name = "Averos FZCO"},
{.companyCode = 0x04BF, .name = "VIT Initiative, LLC"},
{.companyCode = 0x04C0, .name = "Statsports International"},
{.companyCode = 0x04C1, .name = "Sospitas, s.r.o."},
{.companyCode = 0x04C2, .name = "Dmet Products Corp."},
{.companyCode = 0x04C3, .name = "Mantracourt Electronics Limited"},
{.companyCode = 0x04C4, .name = "TeAM Hutchins AB"},
{.companyCode = 0x04C5, .name = "Seibert Williams Glass, LLC"},
{.companyCode = 0x04C6, .name = "Insta GmbH"},
{.companyCode = 0x04C7, .name = "Svantek Sp. z o.o."},
{.companyCode = 0x04C8, .name = "Shanghai Flyco Electrical Appliance Co., Ltd."},
{.companyCode = 0x04C9, .name = "Thornwave Labs Inc"},
{.companyCode = 0x04CA, .name = "Steiner-Optik GmbH"},
{.companyCode = 0x04CB, .name = "Novo Nordisk A/S"},
{.companyCode = 0x04CC, .name = "Enflux Inc."},
{.companyCode = 0x04CD, .name = "Safetech Products LLC"},
{.companyCode = 0x04CE, .name = "GOOOLED S.R.L."},
{.companyCode = 0x04CF, .name = "DOM Sicherheitstechnik GmbH & Co. KG"},
{.companyCode = 0x04D0, .name = "Olympus Corporation"},
{.companyCode = 0x04D1, .name = "KTS GmbH"},
{.companyCode = 0x04D2, .name = "Anloq Technologies Inc."},
{.companyCode = 0x04D3, .name = "Queercon, Inc"},
{.companyCode = 0x04D4, .name = "5th Element Ltd"},
{.companyCode = 0x04D5, .name = "Gooee Limited"},
{.companyCode = 0x04D6, .name = "LUGLOC LLC"},
{.companyCode = 0x04D7, .name = "Blincam, Inc."},
{.companyCode = 0x04D8, .name = "FUJIFILM Corporation"},
{.companyCode = 0x04D9, .name = "RandMcNally"},
{.companyCode = 0x04DA, .name = "Franceschi Marina snc"},
{.companyCode = 0x04DB, .name = "Engineered Audio, LLC."},
{.companyCode = 0x04DC, .name = "IOTTIVE (OPC) PRIVATE LIMITED"},
{.companyCode = 0x04DD, .name = "4MOD Technology"},
{.companyCode = 0x04DE, .name = "Lutron Electronics Co., Inc."},
{.companyCode = 0x04DF, .name = "Emerson"},
{.companyCode = 0x04E0, .name = "Guardtec, Inc."},
{.companyCode = 0x04E1, .name = "REACTEC LIMITED"},
{.companyCode = 0x04E2, .name = "EllieGrid"},
{.companyCode = 0x04E3, .name = "Under Armour"},
{.companyCode = 0x04E4, .name = "Woodenshark"},
{.companyCode = 0x04E5, .name = "Avack Oy"},
{.companyCode = 0x04E6, .name = "Smart Solution Technology, Inc. "},
{.companyCode = 0x04E7, .name = "REHABTRONICS INC. "},
{.companyCode = 0x04E8, .name = "STABILO International"},
{.companyCode = 0x04E9, .name = "Busch Jaeger Elektro GmbH"},
{.companyCode = 0x04EA, .name = "Pacific Bioscience Laboratories, Inc"},
{.companyCode = 0x04EB, .name = "Bird Home Automation GmbH"},
{.companyCode = 0x04EC, .name = "Motorola Solutions"},
{.companyCode = 0x04ED, .name = "R9 Technology, Inc."},
{.companyCode = 0x04EE, .name = "Auxivia"},
{.companyCode = 0x04EF, .name = "DaisyWorks, Inc"},
{.companyCode = 0x04F0, .name = "Kosi Limited"},
{.companyCode = 0x04F1, .name = "Theben AG"},
{.companyCode = 0x04F2, .name = "InDreamer Techsol Private Limited"},
{.companyCode = 0x04F3, .name = "Cerevast Medical"},
{.companyCode = 0x04F4, .name = "ZanCompute Inc."},
{.companyCode = 0x04F5, .name = "Pirelli Tyre S.P.A."},
{.companyCode = 0x04F6, .name = "McLear Limited"},
{.companyCode = 0x04F7, .name = "Shenzhen Huiding Technology Co.,Ltd."},
{.companyCode = 0x04F8, .name = "Convergence Systems Limited"},
{.companyCode = 0x04F9, .name = "Interactio"},
{.companyCode = 0x04FA, .name = "Androtec GmbH"},
{.companyCode = 0x04FB, .name = "Benchmark Drives GmbH & Co. KG"},
{.companyCode = 0x04FC, .name = "SwingLync L. L. C."},
{.companyCode = 0x04FD, .name = "Tapkey GmbH"},
{.companyCode = 0x04FE, .name = "Woosim Systems Inc."},
{.companyCode = 0x04FF, .name = "Microsemi Corporation"},
{.companyCode = 0x0500, .name = "Wiliot LTD."},
{.companyCode = 0x0501, .name = "Polaris IND"},
{.companyCode = 0x0502, .name = "Specifi-Kali LLC"},
{.companyCode = 0x0503, .name = "Locoroll, Inc"},
{.companyCode = 0x0504, .name = "PHYPLUS Inc"},
{.companyCode = 0x0505, .name = "Inplay Technologies LLC"},
{.companyCode = 0x0506, .name = "Hager"},
{.companyCode = 0x0507, .name = "Yellowcog"},
{.companyCode = 0x0508, .name = "Axes System sp. z o. o."},
{.companyCode = 0x0509, .name = "myLIFTER Inc."},
{.companyCode = 0x050A, .name = "Shake-on B.V."},
{.companyCode = 0x050B, .name = "Vibrissa Inc."},
{.companyCode = 0x050C, .name = "OSRAM GmbH"},
{.companyCode = 0x050D, .name = "TRSystems GmbH"},
{.companyCode = 0x050E, .name = "Yichip Microelectronics (Hangzhou) Co.,Ltd."},
{.companyCode = 0x050F, .name = "Foundation Engineering LLC"},
{.companyCode = 0x0510, .name = "UNI-ELECTRONICS, INC."},
{.companyCode = 0x0511, .name = "Brookfield Equinox LLC"},
{.companyCode = 0x0512, .name = "Soprod SA"},
{.companyCode = 0x0513, .name = "9974091 Canada Inc."},
{.companyCode = 0x0514, .name = "FIBRO GmbH"},
{.companyCode = 0x0515, .name = "RB Controls Co., Ltd."},
{.companyCode = 0x0516, .name = "Footmarks"},
{.companyCode = 0x0517, .name = "Amcore AB"},
{.companyCode = 0x0518, .name = "MAMORIO.inc"},
{.companyCode = 0x0519, .name = "Tyto Life LLC"},
{.companyCode = 0x051A, .name = "Leica Camera AG"},
{.companyCode = 0x051B, .name = "Angee Technologies Ltd."},
{.companyCode = 0x051C, .name = "EDPS"},
{.companyCode = 0x051D, .name = "OFF Line Co., Ltd."},
{.companyCode = 0x051E, .name = "Detect Blue Limited"},
{.companyCode = 0x051F, .name = "Setec Pty Ltd"},
{.companyCode = 0x0520, .name = "Target Corporation"},
{.companyCode = 0x0521, .name = "IAI Corporation"},
{.companyCode = 0x0522, .name = "NS Tech, Inc."},
{.companyCode = 0x0523, .name = "MTG Co., Ltd."},
{.companyCode = 0x0524, .name = "Hangzhou iMagic Technology Co., Ltd"},
{.companyCode = 0x0525, .name = "HONGKONG NANO IC TECHNOLOGIES  CO., LIMITED"},
{.companyCode = 0x0526, .name = "Honeywell International Inc."},
{.companyCode = 0x0527, .name = "Albrecht JUNG"},
{.companyCode = 0x0528, .name = "Lunera Lighting Inc."},
{.companyCode = 0x0529, .name = "Lumen UAB"},
{.companyCode = 0x052A, .name = "Keynes Controls Ltd"},
{.companyCode = 0x052B, .name = "Novartis AG"},
{.companyCode = 0x052C, .name = "Geosatis SA"},
{.companyCode = 0x052D, .name = "EXFO, Inc."},
{.companyCode = 0x052E, .name = "LEDVANCE GmbH"},
{.companyCode = 0x052F, .name = "Center ID Corp."},
{.companyCode = 0x0530, .name = "Adolene, Inc."},
{.companyCode = 0x0531, .name = "D&M Holdings Inc."},
{.companyCode = 0x0532, .name = "CRESCO Wireless, Inc."},
{.companyCode = 0x0533, .name = "Nura Operations Pty Ltd"},
{.companyCode = 0x0534, .name = "Frontiergadget, Inc."},
{.companyCode = 0x0535, .name = "Smart Component Technologies Limited"},
{.companyCode = 0x0536, .name = "ZTR Control Systems LLC"},
{.companyCode = 0x0537, .name = "MetaLogics Corporation"},
{.companyCode = 0x0538, .name = "Medela AG"},
{.companyCode = 0x0539, .name = "OPPLE Lighting Co., Ltd"},
{.companyCode = 0x053A, .name = "Savitech Corp.,"},
{.companyCode = 0x053B, .name = "prodigy"},
{.companyCode = 0x053C, .name = "Screenovate Technologies Ltd"},
{.companyCode = 0x053D, .name = "TESA SA"},
{.companyCode = 0x053E, .name = "CLIM8 LIMITED"},
{.companyCode = 0x053F, .name = "Silergy Corp"},
{.companyCode = 0x0540, .name = "SilverPlus, Inc"},
{.companyCode = 0x0541, .name = "Sharknet srl"},
{.companyCode = 0x0542, .name = "Mist Systems, Inc."},
{.companyCode = 0x0543, .name = "MIWA LOCK CO.,Ltd"},
{.companyCode = 0x0544, .name = "OrthoSensor, Inc."},
{.companyCode = 0x0545, .name = "Candy Hoover Group s.r.l"},
{.companyCode = 0x0546, .name = "Apexar Technologies S.A."},
{.companyCode = 0x0547, .name = "LOGICDATA d.o.o."},
{.companyCode = 0x0548, .name = "Knick Elektronische Messgeraete GmbH & Co. KG"},
{.companyCode = 0x0549, .name = "Smart Technologies and Investment Limited"},
{.companyCode = 0x054A, .name = "Linough Inc."},
{.companyCode = 0x054B, .name = "Advanced Electronic Designs, Inc."},
{.companyCode = 0x054C, .name = "Carefree Scott Fetzer Co Inc"},
{.companyCode = 0x054D, .name = "Sensome"},
{.companyCode = 0x054E, .name = "FORTRONIK storitve d.o.o."},
{.companyCode = 0x054F, .name = "Sinnoz"},
{.companyCode = 0x0550, .name = "Versa Networks, Inc."},
{.companyCode = 0x0551, .name = "Sylero"},
{.companyCode = 0x0552, .name = "Avempace SARL"},
{.companyCode = 0x0553, .name = "Nintendo Co., Ltd."},
{.companyCode = 0x0554, .name = "National Instruments"},
{.companyCode = 0x0555, .name = "KROHNE Messtechnik GmbH"},
{.companyCode = 0x0556, .name = "Otodynamics Ltd"},
{.companyCode = 0x0557, .name = "Arwin Technology Limited"},
{.companyCode = 0x0558, .name = "benegear, inc."},
{.companyCode = 0x0559, .name = "Newcon Optik"},
{.companyCode = 0x055A, .name = "CANDY HOUSE, Inc."},
{.companyCode = 0x055B, .name = "FRANKLIN TECHNOLOGY INC"},
{.companyCode = 0x055C, .name = "Lely"},
{.companyCode = 0x055D, .name = "Valve Corporation"},
{.companyCode = 0x055E, .name = "Hekatron Vertriebs GmbH"},
{.companyCode = 0x055F, .name = "PROTECH S.A.S. DI GIRARDI ANDREA & C."},
{.companyCode = 0x0560, .name = "Sarita CareTech IVS"},
{.companyCode = 0x0561, .name = "Finder S.p.A."},
{.companyCode = 0x0562, .name = "Thalmic Labs Inc."},
{.companyCode = 0x0563, .name = "Steinel Vertrieb GmbH"},
{.companyCode = 0x0564, .name = "Beghelli Spa"},
{.companyCode = 0x0565, .name = "Beijing Smartspace Technologies Inc."},
{.companyCode = 0x0566, .name = "CORE TRANSPORT TECHNOLOGIES NZ LIMITED"},
{.companyCode = 0x0567, .name = "Xiamen Everesports Goods Co., Ltd"},
{.companyCode = 0x0568, .name = "Bodyport Inc."},
{.companyCode = 0x0569, .name = "Audionics System, INC."},
{.companyCode = 0x056A, .name = "Flipnavi Co.,Ltd."},
{.companyCode = 0x056B, .name = "Rion Co., Ltd."},
{.companyCode = 0x056C, .name = "Long Range Systems, LLC"},
{.companyCode = 0x056D, .name = "Redmond Industrial Group LLC"},
{.companyCode = 0x056E, .name = "VIZPIN INC."},
{.companyCode = 0x056F, .name = "BikeFinder AS"},
{.companyCode = 0x0570, .name = "Consumer Sleep Solutions LLC"},
{.companyCode = 0x0571, .name = "PSIKICK, INC."},
{.companyCode = 0x0572, .name = "AntTail.com"},
{.companyCode = 0x0573, .name = "Lighting Science Group Corp."},
{.companyCode = 0x0574, .name = "AFFORDABLE ELECTRONICS INC"},
{.companyCode = 0x0575, .name = "Integral Memroy Plc"},
{.companyCode = 0x0576, .name = "Globalstar, Inc."},
{.companyCode = 0x0577, .name = "True Wearables, Inc."},
{.companyCode = 0x0578, .name = "Wellington Drive Technologies Ltd"},
{.companyCode = 0x0579, .name = "Ensemble Tech Private Limited"},
{.companyCode = 0x057A, .name = "OMNI Remotes"},
{.companyCode = 0x057B, .name = "Duracell U.S. Operations Inc."},
{.companyCode = 0x057C, .name = "Toor Technologies LLC"},
{.companyCode = 0x057D, .name = "Instinct Performance"},
{.companyCode = 0x057E, .name = "Beco, Inc"},
{.companyCode = 0x057F, .name = "Scuf Gaming International, LLC"},
{.companyCode = 0x0580, .name = "ARANZ Medical Limited"},
{.companyCode = 0x0581, .name = "LYS TECHNOLOGIES LTD"},
{.companyCode = 0x0582, .name = "Breakwall Analytics, LLC"},
{.companyCode = 0x0583, .name = "Code Blue Communications"},
{.companyCode = 0x0584, .name = "Gira Giersiepen GmbH & Co. KG"},
{.companyCode = 0x0585, .name = "Hearing Lab Technology"},
{.companyCode = 0x0586, .name = "LEGRAND"},
{.companyCode = 0x0587, .name = "Derichs GmbH"},
{.companyCode = 0x0588, .name = "ALT-TEKNIK LLC"},
{.companyCode = 0x0589, .name = "Star Technologies"},
{.companyCode = 0x058A, .name = "START TODAY CO.,LTD."},
{.companyCode = 0x058B, .name = "Maxim Integrated Products"},
{.companyCode = 0x058C, .name = "MERCK Kommanditgesellschaft auf Aktien"},
{.companyCode = 0x058D, .name = "Jungheinrich Aktiengesellschaft"},
{.companyCode = 0x058E, .name = "Oculus VR, LLC"},
{.companyCode = 0x058F, .name = "HENDON SEMICONDUCTORS PTY LTD"},
{.companyCode = 0x0590, .name = "Pur3 Ltd"},
{.companyCode = 0x0591, .name = "Viasat Group S.p.A."},
{.companyCode = 0x0592, .name = "IZITHERM"},
{.companyCode = 0x0593, .name = "Spaulding Clinical Research"},
{.companyCode = 0x0594, .name = "Kohler Company"},
{.companyCode = 0x0595, .name = "Inor Process AB"},
{.companyCode = 0x0596, .name = "My Smart Blinds"},
{.companyCode = 0x0597, .name = "RadioPulse Inc"},
{.companyCode = 0x0598, .name = "rapitag GmbH"},
{.companyCode = 0x0599, .name = "Lazlo326, LLC."},
{.companyCode = 0x059A, .name = "Teledyne Lecroy, Inc."},
{.companyCode = 0x059B, .name = "Dataflow Systems Limited"},
{.companyCode = 0x059C, .name = "Macrogiga Electronics"},
{.companyCode = 0x059D, .name = "Tandem Diabetes Care"},
{.companyCode = 0x059E, .name = "Polycom, Inc."},
{.companyCode = 0x059F, .name = "Fisher & Paykel Healthcare"},
{.companyCode = 0x05A0, .name = "RCP Software Oy"},
{.companyCode = 0x05A1, .name = "Shanghai Xiaoyi Technology Co.,Ltd."},
{.companyCode = 0x05A2, .name = "ADHERIUM(NZ) LIMITED"},
{.companyCode = 0x05A3, .name = "Axiomware Systems Incorporated"},
{.companyCode = 0x05A4, .name = "O. E. M. Controls, Inc."},
{.companyCode = 0x05A5, .name = "Kiiroo BV"},
{.companyCode = 0x05A6, .name = "Telecon Mobile Limited"},
{.companyCode = 0x05A7, .name = "Sonos Inc"},
{.companyCode = 0x05A8, .name = "Tom Allebrandi Consulting"},
{.companyCode = 0x05A9, .name = "Monidor"},
{.companyCode = 0x05AA, .name = "Tramex Limited"},
{.companyCode = 0x05AB, .name = "Nofence AS"},
{.companyCode = 0x05AC, .name = "GoerTek Dynaudio Co., Ltd."},
{.companyCode = 0x05AD, .name = "INIA"},
{.companyCode = 0x05AE, .name = "CARMATE MFG.CO.,LTD"},
{.companyCode = 0x05AF, .name = "ONvocal"},
{.companyCode = 0x05B0, .name = "NewTec GmbH"},
{.companyCode = 0x05B1, .name = "Medallion Instrumentation Systems"},
{.companyCode = 0x05B2, .name = "CAREL INDUSTRIES S.P.A."},
{.companyCode = 0x05B3, .name = "Parabit Systems, Inc."},
{.companyCode = 0x05B4, .name = "White Horse Scientific ltd"},
{.companyCode = 0x05B5, .name = "verisilicon"},
{.companyCode = 0x05B6, .name = "Elecs Industry Co.,Ltd."},
{.companyCode = 0x05B7, .name = "Beijing Pinecone Electronics Co.,Ltd."},
{.companyCode = 0x05B8, .name = "Ambystoma Labs Inc."},
{.companyCode = 0x05B9, .name = "Suzhou Pairlink Network Technology"},
{.companyCode = 0x05BA, .name = "igloohome"},
{.companyCode = 0x05BB, .name = "Oxford Metrics plc"},
{.companyCode = 0x05BC, .name = "Leviton Mfg. Co., Inc."},
{.companyCode = 0x05BD, .name = "ULC Robotics Inc."},
{.companyCode = 0x05BE, .name = "RFID Global by Softwork SrL"},
{.companyCode = 0x05BF, .name = "Real-World-Systems Corporation"},
{.companyCode = 0x05C0, .name = "Nalu Medical, Inc."},
{.companyCode = 0x05C1, .name = "P.I.Engineering"},
{.companyCode = 0x05C2, .name = "Grote Industries"},
{.companyCode = 0x05C3, .name = "Runtime, Inc."},
{.companyCode = 0x05C4, .name = "Codecoup sp. z o.o. sp. k."},
{.companyCode = 0x05C5, .name = "SELVE GmbH & Co. KG"},
{.companyCode = 0x05C6, .name = "Smart Animal Training Systems, LLC"},
{.companyCode = 0x05C7, .name = "Lippert Components, INC"},
{.companyCode = 0x05C8, .name = "SOMFY SAS"},
{.companyCode = 0x05C9, .name = "TBS Electronics B.V."},
{.companyCode = 0x05CA, .name = "MHL Custom Inc"},
{.companyCode = 0x05CB, .name = "LucentWear LLC"},
{.companyCode = 0x05CC, .name = "WATTS ELECTRONICS"},
{.companyCode = 0x05CD, .name = "RJ Brands LLC"},
{.companyCode = 0x05CE, .name = "V-ZUG Ltd"},
{.companyCode = 0x05CF, .name = "Biowatch SA"},
{.companyCode = 0x05D0, .name = "Anova Applied Electronics"},
{.companyCode = 0x05D1, .name = "Lindab AB"},
{.companyCode = 0x05D2, .name = "frogblue TECHNOLOGY GmbH"},
{.companyCode = 0x05D3, .name = "Acurable Limited"},
{.companyCode = 0x05D4, .name = "LAMPLIGHT Co., Ltd."},
{.companyCode = 0x05D5, .name = "TEGAM, Inc."},
{.companyCode = 0x05D6, .name = "Zhuhai Jieli technology Co.,Ltd"},
{.companyCode = 0x05D7, .name = "modum.io AG"},
{.companyCode = 0x05D8, .name = "Farm Jenny LLC"},
{.companyCode = 0x05D9, .name = "Toyo Electronics Corporation"},
{.companyCode = 0x05DA, .name = "Applied Neural Research Corp"},
{.companyCode = 0x05DB, .name = "Avid Identification Systems, Inc."},
{.companyCode = 0x05DC, .name = "Petronics Inc."},
{.companyCode = 0x05DD, .name = "essentim GmbH"},
{.companyCode = 0x05DE, .name = "QT Medical INC."},
{.companyCode = 0x05DF, .name = "VIRTUALCLINIC.DIRECT LIMITED"},
{.companyCode = 0x05E0, .name = "Viper Design LLC"},
{.companyCode = 0x05E1, .name = "Human, Incorporated"},
{.companyCode = 0x05E2, .name = "stAPPtronics GmbH"},
{.companyCode = 0x05E3, .name = "Elemental Machines, Inc."},
{.companyCode = 0x05E4, .name = "Taiyo Yuden Co., Ltd"},
{.companyCode = 0x05E5, .name = "INEO ENERGY& SYSTEMS"},
{.companyCode = 0x05E6, .name = "Motion Instruments Inc."},
{.companyCode = 0x05E7, .name = "PressurePro"},
{.companyCode = 0x05E8, .name = "COWBOY"},
{.companyCode = 0x05E9, .name = "iconmobile GmbH"},
{.companyCode = 0x05EA, .name = "ACS-Control-System GmbH"},
{.companyCode = 0x05EB, .name = "Bayerische Motoren Werke AG"},
{.companyCode = 0x05EC, .name = "Gycom Svenska AB"},
{.companyCode = 0x05ED, .name = "Fuji Xerox Co., Ltd"},
{.companyCode = 0x05EE, .name = "Glide Inc."},
{.companyCode = 0x05EF, .name = "SIKOM AS"},
{.companyCode = 0x05F0, .name = "beken"},
{.companyCode = 0x05F1, .name = "The Linux Foundation"},
{.companyCode = 0x05F2, .name = "Try and E CO.,LTD."},
{.companyCode = 0x05F3, .name = "SeeScan"},
{.companyCode = 0x05F4, .name = "Clearity, LLC"},
{.companyCode = 0x05F5, .name = "GS TAG"},
{.companyCode = 0x05F6, .name = "DPTechnics"},
{.companyCode = 0x05F7, .name = "TRACMO, INC."},
{.companyCode = 0x05F8, .name = "Anki Inc."},
{.companyCode = 0x05F9, .name = "Hagleitner Hygiene International GmbH"},
{.companyCode = 0x05FA, .name = "Konami Sports Life Co., Ltd."},
{.companyCode = 0x05FB, .name = "Arblet Inc."},
{.companyCode = 0x05FC, .name = "Masbando GmbH"},
{.companyCode = 0x05FD, .name = "Innoseis"},
{.companyCode = 0x05FE, .name = "Niko"},
{.companyCode = 0x05FF, .name = "Wellnomics Ltd"},
{.companyCode = 0x0600, .name = "iRobot Corporation"},
{.companyCode = 0x0601, .name = "Schrader Electronics"},
{.companyCode = 0x0602, .name = "Geberit International AG"},
{.companyCode = 0x0603, .name = "Fourth Evolution Inc"},
{.companyCode = 0x0604, .name = "Cell2Jack LLC"},
{.companyCode = 0x0605, .name = "FMW electronic Futterer u. Maier-Wolf OHG"},
{.companyCode = 0x0606, .name = "John Deere"},
{.companyCode = 0x0607, .name = "Rookery Technology Ltd"},
{.companyCode = 0x0608, .name = "KeySafe-Cloud"},
{.companyCode = 0x0609, .name = "BUCHI Labortechnik AG"},
{.companyCode = 0x060A, .name = "IQAir AG"},
{.companyCode = 0x060B, .name = "Triax Technologies Inc"},
{.companyCode = 0x060C, .name = "Vuzix Corporation"},
{.companyCode = 0x060D, .name = "TDK Corporation"},
{.companyCode = 0x060E, .name = "Blueair AB"},
{.companyCode = 0x060F, .name = "Signify Netherlands "},
{.companyCode = 0x0610, .name = "ADH GUARDIAN USA LLC"},
{.companyCode = 0x0611, .name = "Beurer GmbH"},
{.companyCode = 0x0612, .name = "Playfinity AS"},
{.companyCode = 0x0613, .name = "Hans Dinslage GmbH"},
{.companyCode = 0x0614, .name = "OnAsset Intelligence, Inc."},
{.companyCode = 0x0615, .name = "INTER ACTION Corporation"},
{.companyCode = 0x0616, .name = "OS42 UG (haftungsbeschraenkt)"},
{.companyCode = 0x0617, .name = "WIZCONNECTED COMPANY LIMITED"},
{.companyCode = 0x0618, .name = "Audio-Technica Corporation"},
{.companyCode = 0x0619, .name = "Six Guys Labs, s.r.o."},
{.companyCode = 0x061A, .name = "R.W. Beckett Corporation"},
{.companyCode = 0x061B, .name = "silex technology, inc."},
{.companyCode = 0x061C, .name = "Univations Limited"},
{.companyCode = 0x061D, .name = "SENS Innovation ApS"},
{.companyCode = 0x061E, .name = "Diamond Kinetics, Inc."},
{.companyCode = 0x061F, .name = "Phrame Inc."},
{.companyCode = 0x0620, .name = "Forciot Oy"},
{.companyCode = 0x0621, .name = "Noordung d.o.o."},
{.companyCode = 0x0622, .name = "Beam Labs, LLC"},
{.companyCode = 0x0623, .name = "Philadelphia Scientific (U.K.) Limited"},
{.companyCode = 0x0624, .name = "Biovotion AG"},
{.companyCode = 0x0625, .name = "Square Panda, Inc."},
{.companyCode = 0x0626, .name = "Amplifico"},
{.companyCode = 0x0627, .name = "WEG S.A."},
{.companyCode = 0x0628, .name = "Ensto Oy"},
{.companyCode = 0x0629, .name = "PHONEPE PVT LTD"},
{.companyCode = 0x062A, .name = "Lunatico Astronomia SL"},
{.companyCode = 0x062B, .name = "MinebeaMitsumi Inc."},
{.companyCode = 0x062C, .name = "ASPion GmbH"},
{.companyCode = 0x062D, .name = "Vossloh-Schwabe Deutschland GmbH"},
{.companyCode = 0x062E, .name = "Procept"},
{.companyCode = 0x062F, .name = "ONKYO Corporation"},
{.companyCode = 0x0630, .name = "Asthrea D.O.O."},
{.companyCode = 0x0631, .name = "Fortiori Design LLC"},
{.companyCode = 0x0632, .name = "Hugo Muller GmbH & Co KG"},
{.companyCode = 0x0633, .name = "Wangi Lai PLT"},
{.companyCode = 0x0634, .name = "Fanstel Corp"},
{.companyCode = 0x0635, .name = "Crookwood"},
{.companyCode = 0x0636, .name = "ELECTRONICA INTEGRAL DE SONIDO S.A."},
{.companyCode = 0x0637, .name = "GiP Innovation Tools GmbH"},
{.companyCode = 0x0638, .name = "LX SOLUTIONS PTY LIMITED"},
{.companyCode = 0x0639, .name = "Shenzhen Minew Technologies Co., Ltd."},
{.companyCode = 0x063A, .name = "Prolojik Limited"},
{.companyCode = 0x063B, .name = "Kromek Group Plc"},
{.companyCode = 0x063C, .name = "Contec Medical Systems Co., Ltd."},
{.companyCode = 0x063D, .name = "Xradio Technology Co.,Ltd."},
{.companyCode = 0x063E, .name = "The Indoor Lab, LLC"},
{.companyCode = 0x063F, .name = "LDL TECHNOLOGY"},
{.companyCode = 0x0640, .name = "Parkifi"},
{.companyCode = 0x0641, .name = "Revenue Collection Systems FRANCE SAS"},
{.companyCode = 0x0642, .name = "Bluetrum Technology Co.,Ltd"},
{.companyCode = 0x0643, .name = "makita corporation"},
{.companyCode = 0x0644, .name = "Apogee Instruments"},
{.companyCode = 0x0645, .name = "BM3"},
{.companyCode = 0x0646, .name = "SGV Group Holding GmbH & Co. KG"},
{.companyCode = 0x0647, .name = "MED-EL"},
{.companyCode = 0x0648, .name = "Ultune Technologies"},
{.companyCode = 0x0649, .name = "Ryeex Technology Co.,Ltd."},
{.companyCode = 0x064A, .name = "Open Research Institute, Inc."},
{.companyCode = 0x064B, .name = "Scale-Tec, Ltd"},
{.companyCode = 0x064C, .name = "Zumtobel Group AG"},
{.companyCode = 0x064D, .name = "iLOQ Oy"},
{.companyCode = 0x064E, .name = "KRUXWorks Technologies Private Limited"},
{.companyCode = 0x064F, .name = "Digital Matter Pty Ltd"},
{.companyCode = 0x0650, .name = "Coravin, Inc."},
{.companyCode = 0x0651, .name = "Stasis Labs, Inc."},
{.companyCode = 0x0652, .name = "ITZ Innovations- und Technologiezentrum GmbH"},
{.companyCode = 0x0653, .name = "Meggitt SA"},
{.companyCode = 0x0654, .name = "Ledlenser GmbH & Co. KG"},
{.companyCode = 0x0655, .name = "Renishaw PLC"},
{.companyCode = 0x0656, .name = "ZhuHai AdvanPro Technology Company Limited"},
{.companyCode = 0x0657, .name = "Meshtronix Limited"},
{.companyCode = 0x0658, .name = "Payex Norge AS"},
{.companyCode = 0x0659, .name = "UnSeen Technologies Oy"},
{.companyCode = 0x065A, .name = "Zound Industries International AB"},
{.companyCode = 0x065B, .name = "Sesam Solutions BV"},
{.companyCode = 0x065C, .name = "PixArt Imaging Inc."},
{.companyCode = 0x065D, .name = "Panduit Corp."},
{.companyCode = 0xFFFF, .name = "This value has special meaning depending on the context in which it used.\nLink Manager Protocol (LMP): This value may be used in the internal and interoperability tests before a Company ID has been assigned. This value shall not be used in shipping end products.\nDevice ID Profile: This value is reserved as the default vendor ID when no Device ID service record is present in a remote device."},
};

uint32_t numCompanies = sizeof(company_ids)/sizeof(company_id_t);

char *getCompanyName(uint16_t id)
{
    for(int i=0;i<numCompanies;i++)
        if(company_ids[i].companyCode == id)
            return company_ids[i].name;
    return 0;
}

