/***************************************************************************//**
* File Name: cycfg_gatt_db.h
* Version: 1.1
*
* Description:
* Definitions for constants used in the device's GATT database and function
* prototypes.
* This file should not be modified. It was automatically generated by
* Bluetooth Configurator 1.1.0 build 291
*
********************************************************************************
* Copyright 2019 Cypress Semiconductor Corporation
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#if !defined(CYCFG_GATT_DB_H)
#define CYCFG_GATT_DB_H

#include "stdint.h"

#define __UUID_SERVICE_GENERIC_ACCESS               0x1800u
#define __UUID_CHARACTERISTIC_DEVICE_NAME           0x2A00u
#define __UUID_CHARACTERISTIC_APPEARANCE            0x2A01u
#define __UUID_SERVICE_GENERIC_ATTRIBUTE            0x1801u
#define __UUID_SERVICE_MODUSLED                     0x90u, 0xDFu, 0x43u, 0x89u, 0x42u, 0x0Eu, 0xC2u, 0xB4u, 0xF7u, 0x44u, 0xBBu, 0x7Du, 0xE1u, 0xACu, 0x16u, 0x50u
#define __UUID_CHARACTERISTIC_MODUSLED_LED          0x37u, 0xD2u, 0x41u, 0x8Du, 0x7Bu, 0x62u, 0x58u, 0x83u, 0x04u, 0x41u, 0xA9u, 0x26u, 0xC3u, 0x76u, 0xDBu, 0xABu

/* Service Generic Access */
#define HDLS_GAP                                    0x0001u
/* Characteristic Device Name */
#define HDLC_GAP_DEVICE_NAME                        0x0002u
#define HDLC_GAP_DEVICE_NAME_VALUE                  0x0003u
/* Characteristic Appearance */
#define HDLC_GAP_APPEARANCE                         0x0004u
#define HDLC_GAP_APPEARANCE_VALUE                   0x0005u

/* Service Generic Attribute */
#define HDLS_GATT                                   0x0006u

/* Service ModusLED */
#define HDLS_MODUSLED                               0x0007u
/* Characteristic LED */
#define HDLC_MODUSLED_LED                           0x0008u
#define HDLC_MODUSLED_LED_VALUE                     0x0009u

/* External Lookup Table Entry */
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table_t;

/* External definitions */
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table_t app_gatt_db_ext_attr_tbl[];
extern const uint16_t app_gatt_db_ext_attr_tbl_size;
extern uint8_t app_gap_device_name[];
extern const uint16_t app_gap_device_name_len;
extern uint8_t app_gap_appearance[];
extern const uint16_t app_gap_appearance_len;
extern uint8_t app_modusled_led[];
extern const uint16_t app_modusled_led_len;

#endif /* CYCFG_GATT_DB_H */

