/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * Definitions for constants used in the device's SDP database.
 *
 */

// key_ClassicSpp_sdp_db.h

#ifndef __SDP_DATABASE_H__
#define __SDP_DATABASE_H__

// SDP Record for Serial Port
#define HDLR_SERIAL_PORT               0x10001
#define SERIAL_PORT_SCN                0x01
// SDP Record for Device ID
#define HDLR_DEVICE_ID                 0x10002

// External definitions
extern const uint8_t  sdp_database[];
extern const uint16_t sdp_database_len;

#endif /* __SDP_DATABASE_H__ */
