/*
 * This file has been automatically generated by the WICED 20719-B1 Designer.
 * Definitions for constants used in the device's GATT database and function
 * prototypes.
 *
 */

// ex06_ota_secure_db.h

#ifndef __GATT_DATABASE_H__
#define __GATT_DATABASE_H__

#define __UUID_WICEDLED                       0xed, 0x4e, 0x7e, 0xd0, 0xcd, 0x55, 0x4e, 0xe1, 0x9c, 0x99, 0x34, 0x2e, 0x3c, 0xda, 0x86, 0x2d
#define __UUID_WICEDLED_LED                   0x24, 0x6a, 0x66, 0x04, 0xef, 0xdd, 0x45, 0xe0, 0xaf, 0x57, 0x43, 0xdf, 0x1f, 0x56, 0x83, 0xc4

// ***** Primary Service 'Generic Attribute'
#define HDLS_GENERIC_ATTRIBUTE                0x0001

// ***** Primary Service 'Generic Access'
#define HDLS_GENERIC_ACCESS                   0x0014
// ----- Characteristic 'Device Name'
#define HDLC_GENERIC_ACCESS_DEVICE_NAME       0x0015
#define HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE 0x0016
// ----- Characteristic 'Appearance'
#define HDLC_GENERIC_ACCESS_APPEARANCE        0x0017
#define HDLC_GENERIC_ACCESS_APPEARANCE_VALUE  0x0018

// ***** Primary Service 'WicedLED'
#define HDLS_WICEDLED                         0x0028
// ----- Characteristic 'LED'
#define HDLC_WICEDLED_LED                     0x0029
#define HDLC_WICEDLED_LED_VALUE               0x002A

// External Lookup Table Entry
typedef struct
{
    uint16_t handle;
    uint16_t max_len;
    uint16_t cur_len;
    uint8_t  *p_data;
} gatt_db_lookup_table;

// External definitions
extern const uint8_t  gatt_database[];
extern const uint16_t gatt_database_len;
extern gatt_db_lookup_table ex06_ota_secure_gatt_db_ext_attr_tbl[];
extern const uint16_t ex06_ota_secure_gatt_db_ext_attr_tbl_size;
extern uint8_t BT_LOCAL_NAME[];
extern const uint16_t BT_LOCAL_NAME_CAPACITY;

#endif /* __GATT_DATABASE_H__ */
